//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class aspnet_Users : Entity
    {
        
        private Guid _ApplicationId;
        
        private Guid _UserId;
        
        private String _UserName;
        
        private String _LoweredUserName;
        
        private String _MobileAlias;
        
        private Boolean _IsAnonymous;
        
        private DateTime _LastActivityDate;
        
        [DataMember()]
        public Guid ApplicationId
        {
            get
            {
                return _ApplicationId;
            }
            set
            {
                if ((value != _ApplicationId))
                {
                    _ApplicationId = value;
                    OnPropertyChanged("ApplicationId");
                }
            }
        }
        
        [DataMember()]
        public Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if ((value != _UserId))
                {
                    _UserId = value;
                    OnPropertyChanged("UserId");
                }
            }
        }
        
        [DataMember()]
        public String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                if ((value != _UserName))
                {
                    _UserName = value;
                    OnPropertyChanged("UserName");
                }
            }
        }
        
        [DataMember()]
        public String LoweredUserName
        {
            get
            {
                return _LoweredUserName;
            }
            set
            {
                if ((value != _LoweredUserName))
                {
                    _LoweredUserName = value;
                    OnPropertyChanged("LoweredUserName");
                }
            }
        }
        
        [DataMember()]
        public String MobileAlias
        {
            get
            {
                return _MobileAlias;
            }
            set
            {
                if ((value != _MobileAlias))
                {
                    _MobileAlias = value;
                    OnPropertyChanged("MobileAlias");
                }
            }
        }
        
        [DataMember()]
        public Boolean IsAnonymous
        {
            get
            {
                return _IsAnonymous;
            }
            set
            {
                if ((value != _IsAnonymous))
                {
                    _IsAnonymous = value;
                    OnPropertyChanged("IsAnonymous");
                }
            }
        }
        
        [DataMember()]
        public DateTime LastActivityDate
        {
            get
            {
                return _LastActivityDate;
            }
            set
            {
                if ((value != _LastActivityDate))
                {
                    _LastActivityDate = value;
                    OnPropertyChanged("LastActivityDate");
                }
            }
        }
    }
}
