//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class aspnet_Profile : Entity
    {
        
        private Guid _UserId;
        
        private String _PropertyNames;
        
        private String _PropertyValuesString;
        
        private Byte[] _PropertyValuesBinary;
        
        private DateTime _LastUpdatedDate;
        
        [DataMember()]
        public Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if ((value != _UserId))
                {
                    _UserId = value;
                    OnPropertyChanged("UserId");
                }
            }
        }
        
        [DataMember()]
        public String PropertyNames
        {
            get
            {
                return _PropertyNames;
            }
            set
            {
                if ((value != _PropertyNames))
                {
                    _PropertyNames = value;
                    OnPropertyChanged("PropertyNames");
                }
            }
        }
        
        [DataMember()]
        public String PropertyValuesString
        {
            get
            {
                return _PropertyValuesString;
            }
            set
            {
                if ((value != _PropertyValuesString))
                {
                    _PropertyValuesString = value;
                    OnPropertyChanged("PropertyValuesString");
                }
            }
        }
        
        [DataMember()]
        public Byte[] PropertyValuesBinary
        {
            get
            {
                return _PropertyValuesBinary;
            }
            set
            {
                if ((value != _PropertyValuesBinary))
                {
                    _PropertyValuesBinary = value;
                    OnPropertyChanged("PropertyValuesBinary");
                }
            }
        }
        
        [DataMember()]
        public DateTime LastUpdatedDate
        {
            get
            {
                return _LastUpdatedDate;
            }
            set
            {
                if ((value != _LastUpdatedDate))
                {
                    _LastUpdatedDate = value;
                    OnPropertyChanged("LastUpdatedDate");
                }
            }
        }
    }
}
