//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class aspnet_CustomProfile : Entity
    {
        
        private Guid _UserId;
        
        private Guid? _DeptId;
        
        private String _FullName;
        
        private DateTime _LastUpdatedDate;
        
        [DataMember()]
        public Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if ((value != _UserId))
                {
                    _UserId = value;
                    OnPropertyChanged("UserId");
                }
            }
        }
        
        [DataMember()]
        public Guid? DeptId
        {
            get
            {
                return _DeptId;
            }
            set
            {
                if ((value != _DeptId))
                {
                    _DeptId = value;
                    OnPropertyChanged("DeptId");
                }
            }
        }
        
        [DataMember()]
        public String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                if ((value != _FullName))
                {
                    _FullName = value;
                    OnPropertyChanged("FullName");
                }
            }
        }
        
        [DataMember()]
        public DateTime LastUpdatedDate
        {
            get
            {
                return _LastUpdatedDate;
            }
            set
            {
                if ((value != _LastUpdatedDate))
                {
                    _LastUpdatedDate = value;
                    OnPropertyChanged("LastUpdatedDate");
                }
            }
        }
    }
}
