//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class aspnet_Applications : Entity
    {
        
        private String _ApplicationName;
        
        private String _LoweredApplicationName;
        
        private Guid _ApplicationId;
        
        private String _Description;
        
        [DataMember()]
        public String ApplicationName
        {
            get
            {
                return _ApplicationName;
            }
            set
            {
                if ((value != _ApplicationName))
                {
                    _ApplicationName = value;
                    OnPropertyChanged("ApplicationName");
                }
            }
        }
        
        [DataMember()]
        public String LoweredApplicationName
        {
            get
            {
                return _LoweredApplicationName;
            }
            set
            {
                if ((value != _LoweredApplicationName))
                {
                    _LoweredApplicationName = value;
                    OnPropertyChanged("LoweredApplicationName");
                }
            }
        }
        
        [DataMember()]
        public Guid ApplicationId
        {
            get
            {
                return _ApplicationId;
            }
            set
            {
                if ((value != _ApplicationId))
                {
                    _ApplicationId = value;
                    OnPropertyChanged("ApplicationId");
                }
            }
        }
        
        [DataMember()]
        public String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                if ((value != _Description))
                {
                    _Description = value;
                    OnPropertyChanged("Description");
                }
            }
        }
    }
}
