//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class aspnet_SchemaVersions : Entity
    {
        
        private String _Feature;
        
        private String _CompatibleSchemaVersion;
        
        private Boolean _IsCurrentVersion;
        
        [DataMember()]
        public String Feature
        {
            get
            {
                return _Feature;
            }
            set
            {
                if ((value != _Feature))
                {
                    _Feature = value;
                    OnPropertyChanged("Feature");
                }
            }
        }
        
        [DataMember()]
        public String CompatibleSchemaVersion
        {
            get
            {
                return _CompatibleSchemaVersion;
            }
            set
            {
                if ((value != _CompatibleSchemaVersion))
                {
                    _CompatibleSchemaVersion = value;
                    OnPropertyChanged("CompatibleSchemaVersion");
                }
            }
        }
        
        [DataMember()]
        public Boolean IsCurrentVersion
        {
            get
            {
                return _IsCurrentVersion;
            }
            set
            {
                if ((value != _IsCurrentVersion))
                {
                    _IsCurrentVersion = value;
                    OnPropertyChanged("IsCurrentVersion");
                }
            }
        }
    }
}
