//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class aspnet_Membership : Entity
    {
        
        private Guid _ApplicationId;
        
        private Guid _UserId;
        
        private String _Password;
        
        private Int32 _PasswordFormat;
        
        private String _PasswordSalt;
        
        private String _MobilePIN;
        
        private String _Email;
        
        private String _LoweredEmail;
        
        private String _PasswordQuestion;
        
        private String _PasswordAnswer;
        
        private Boolean _IsApproved;
        
        private Boolean _IsLockedOut;
        
        private DateTime _CreateDate;
        
        private DateTime _LastLoginDate;
        
        private DateTime _LastPasswordChangedDate;
        
        private DateTime _LastLockoutDate;
        
        private Int32 _FailedPasswordAttemptCount;
        
        private DateTime _FailedPasswordAttemptWindowStart;
        
        private Int32 _FailedPasswordAnswerAttemptCount;
        
        private DateTime _FailedPasswordAnswerAttemptWindowStart;
        
        private String _Comment;
        
        [DataMember()]
        public Guid ApplicationId
        {
            get
            {
                return _ApplicationId;
            }
            set
            {
                if ((value != _ApplicationId))
                {
                    _ApplicationId = value;
                    OnPropertyChanged("ApplicationId");
                }
            }
        }
        
        [DataMember()]
        public Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if ((value != _UserId))
                {
                    _UserId = value;
                    OnPropertyChanged("UserId");
                }
            }
        }
        
        [DataMember()]
        public String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                if ((value != _Password))
                {
                    _Password = value;
                    OnPropertyChanged("Password");
                }
            }
        }
        
        [DataMember()]
        public Int32 PasswordFormat
        {
            get
            {
                return _PasswordFormat;
            }
            set
            {
                if ((value != _PasswordFormat))
                {
                    _PasswordFormat = value;
                    OnPropertyChanged("PasswordFormat");
                }
            }
        }
        
        [DataMember()]
        public String PasswordSalt
        {
            get
            {
                return _PasswordSalt;
            }
            set
            {
                if ((value != _PasswordSalt))
                {
                    _PasswordSalt = value;
                    OnPropertyChanged("PasswordSalt");
                }
            }
        }
        
        [DataMember()]
        public String MobilePIN
        {
            get
            {
                return _MobilePIN;
            }
            set
            {
                if ((value != _MobilePIN))
                {
                    _MobilePIN = value;
                    OnPropertyChanged("MobilePIN");
                }
            }
        }
        
        [DataMember()]
        public String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                if ((value != _Email))
                {
                    _Email = value;
                    OnPropertyChanged("Email");
                }
            }
        }
        
        [DataMember()]
        public String LoweredEmail
        {
            get
            {
                return _LoweredEmail;
            }
            set
            {
                if ((value != _LoweredEmail))
                {
                    _LoweredEmail = value;
                    OnPropertyChanged("LoweredEmail");
                }
            }
        }
        
        [DataMember()]
        public String PasswordQuestion
        {
            get
            {
                return _PasswordQuestion;
            }
            set
            {
                if ((value != _PasswordQuestion))
                {
                    _PasswordQuestion = value;
                    OnPropertyChanged("PasswordQuestion");
                }
            }
        }
        
        [DataMember()]
        public String PasswordAnswer
        {
            get
            {
                return _PasswordAnswer;
            }
            set
            {
                if ((value != _PasswordAnswer))
                {
                    _PasswordAnswer = value;
                    OnPropertyChanged("PasswordAnswer");
                }
            }
        }
        
        [DataMember()]
        public Boolean IsApproved
        {
            get
            {
                return _IsApproved;
            }
            set
            {
                if ((value != _IsApproved))
                {
                    _IsApproved = value;
                    OnPropertyChanged("IsApproved");
                }
            }
        }
        
        [DataMember()]
        public Boolean IsLockedOut
        {
            get
            {
                return _IsLockedOut;
            }
            set
            {
                if ((value != _IsLockedOut))
                {
                    _IsLockedOut = value;
                    OnPropertyChanged("IsLockedOut");
                }
            }
        }
        
        [DataMember()]
        public DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                if ((value != _CreateDate))
                {
                    _CreateDate = value;
                    OnPropertyChanged("CreateDate");
                }
            }
        }
        
        [DataMember()]
        public DateTime LastLoginDate
        {
            get
            {
                return _LastLoginDate;
            }
            set
            {
                if ((value != _LastLoginDate))
                {
                    _LastLoginDate = value;
                    OnPropertyChanged("LastLoginDate");
                }
            }
        }
        
        [DataMember()]
        public DateTime LastPasswordChangedDate
        {
            get
            {
                return _LastPasswordChangedDate;
            }
            set
            {
                if ((value != _LastPasswordChangedDate))
                {
                    _LastPasswordChangedDate = value;
                    OnPropertyChanged("LastPasswordChangedDate");
                }
            }
        }
        
        [DataMember()]
        public DateTime LastLockoutDate
        {
            get
            {
                return _LastLockoutDate;
            }
            set
            {
                if ((value != _LastLockoutDate))
                {
                    _LastLockoutDate = value;
                    OnPropertyChanged("LastLockoutDate");
                }
            }
        }
        
        [DataMember()]
        public Int32 FailedPasswordAttemptCount
        {
            get
            {
                return _FailedPasswordAttemptCount;
            }
            set
            {
                if ((value != _FailedPasswordAttemptCount))
                {
                    _FailedPasswordAttemptCount = value;
                    OnPropertyChanged("FailedPasswordAttemptCount");
                }
            }
        }
        
        [DataMember()]
        public DateTime FailedPasswordAttemptWindowStart
        {
            get
            {
                return _FailedPasswordAttemptWindowStart;
            }
            set
            {
                if ((value != _FailedPasswordAttemptWindowStart))
                {
                    _FailedPasswordAttemptWindowStart = value;
                    OnPropertyChanged("FailedPasswordAttemptWindowStart");
                }
            }
        }
        
        [DataMember()]
        public Int32 FailedPasswordAnswerAttemptCount
        {
            get
            {
                return _FailedPasswordAnswerAttemptCount;
            }
            set
            {
                if ((value != _FailedPasswordAnswerAttemptCount))
                {
                    _FailedPasswordAnswerAttemptCount = value;
                    OnPropertyChanged("FailedPasswordAnswerAttemptCount");
                }
            }
        }
        
        [DataMember()]
        public DateTime FailedPasswordAnswerAttemptWindowStart
        {
            get
            {
                return _FailedPasswordAnswerAttemptWindowStart;
            }
            set
            {
                if ((value != _FailedPasswordAnswerAttemptWindowStart))
                {
                    _FailedPasswordAnswerAttemptWindowStart = value;
                    OnPropertyChanged("FailedPasswordAnswerAttemptWindowStart");
                }
            }
        }
        
        [DataMember()]
        public String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                if ((value != _Comment))
                {
                    _Comment = value;
                    OnPropertyChanged("Comment");
                }
            }
        }
    }
}
