//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class BillInvLists : Entity
    {
        
        private Guid _Id;
        
        private Guid _Bill;
        
        private String _Name;
        
        private String _CupType;
        
        private String _Tastes;
        
        private Decimal? _SalePrice;
        
        private Decimal? _Quantity;
        
        private Decimal? _Amount;

        private Decimal? _Discount;

        private Decimal? _Sum;

        private Decimal? _AgreementPrice;

        [DataMember()]
        public Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if ((value != _Id))
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public Guid Bill
        {
            get
            {
                return _Bill;
            }
            set
            {
                if ((value != _Bill))
                {
                    _Bill = value;
                    OnPropertyChanged("Bill");
                }
            }
        }
        
        [DataMember()]
        public String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if ((value != _Name))
                {
                    _Name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        
        [DataMember()]
        public String CupType
        {
            get
            {
                return _CupType;
            }
            set
            {
                if ((value != _CupType))
                {
                    _CupType = value;
                    OnPropertyChanged("CupType");
                }
            }
        }
        
        [DataMember()]
        public String Tastes
        {
            get
            {
                return _Tastes;
            }
            set
            {
                if ((value != _Tastes))
                {
                    _Tastes = value;
                    OnPropertyChanged("Tastes");
                }
            }
        }
        
        [DataMember()]
        public Decimal? SalePrice
        {
            get
            {
                return _SalePrice;
            }
            set
            {
                if ((value != _SalePrice))
                {
                    _SalePrice = value;
                    OnPropertyChanged("SalePrice");
                }
            }
        }
        
        [DataMember()]
        public Decimal? Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                if ((value != _Quantity))
                {
                    _Quantity = value;
                    OnPropertyChanged("Quantity");
                }
            }
        }
        
        [DataMember()]
        public Decimal? Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                if ((value != _Amount))
                {
                    _Amount = value;
                    OnPropertyChanged("Amount");
                }
            }
        }

        [DataMember()]
        public Decimal? Discount
        {
            get
            {
                return _Discount;
            }
            set
            {
                if ((value != _Discount))
                {
                    _Discount = value;
                    OnPropertyChanged("Discount");
                }
            }
        }

        [DataMember()]
        public Decimal? Sum
        {
            get
            {
                return _Sum;
            }
            set
            {
                if ((value != _Sum))
                {
                    _Sum = value;
                    OnPropertyChanged("Sum");
                }
            }
        }

        [DataMember()]
        public Decimal? AgreementPrice
        {
            get
            {
                return _AgreementPrice;
            }
            set
            {
                if ((value != _AgreementPrice))
                {
                    _AgreementPrice = value;
                    OnPropertyChanged("AgreementPrice");
                }
            }
        }
    }
}
