//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class BillOfMaterials : Entity
    {
        
        private Guid _Id;
        
        private Guid _PartInvId;
        
        private Guid _ComponentInvId;
        
        private Decimal _BaseQtyN;
        
        private Decimal _BaseQtyD;
        
        [DataMember()]
        public Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if ((value != _Id))
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public Guid PartInvId
        {
            get
            {
                return _PartInvId;
            }
            set
            {
                if ((value != _PartInvId))
                {
                    _PartInvId = value;
                    OnPropertyChanged("PartInvId");
                }
            }
        }
        
        [DataMember()]
        public Guid ComponentInvId
        {
            get
            {
                return _ComponentInvId;
            }
            set
            {
                if ((value != _ComponentInvId))
                {
                    _ComponentInvId = value;
                    OnPropertyChanged("ComponentInvId");
                }
            }
        }
        
        [DataMember()]
        public Decimal BaseQtyN
        {
            get
            {
                return _BaseQtyN;
            }
            set
            {
                if ((value != _BaseQtyN))
                {
                    _BaseQtyN = value;
                    OnPropertyChanged("BaseQtyN");
                }
            }
        }
        
        [DataMember()]
        public Decimal BaseQtyD
        {
            get
            {
                return _BaseQtyD;
            }
            set
            {
                if ((value != _BaseQtyD))
                {
                    _BaseQtyD = value;
                    OnPropertyChanged("BaseQtyD");
                }
            }
        }
    }
}
