//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class BillDonateInvLists : Entity
    {
        
        private Guid _Id;
        
        private Guid _Bill;
        
        private String _InvName;
        
        [DataMember()]
        public Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if ((value != _Id))
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public Guid Bill
        {
            get
            {
                return _Bill;
            }
            set
            {
                if ((value != _Bill))
                {
                    _Bill = value;
                    OnPropertyChanged("Bill");
                }
            }
        }
        
        [DataMember()]
        public String InvName
        {
            get
            {
                return _InvName;
            }
            set
            {
                if ((value != _InvName))
                {
                    _InvName = value;
                    OnPropertyChanged("InvName");
                }
            }
        }
    }
}
