//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class CardTypes : Entity
    {
        
        private Guid _Id;
        
        private String _Code;
        
        private String _Name;
        
        private String _Comment;
        
        private Boolean _IsMoney;

        private Boolean _IsVirtual;

        private String _CardNoRule;

        [DataMember()]
        public Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if ((value != _Id))
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if ((value != _Code))
                {
                    _Code = value;
                    OnPropertyChanged("Code");
                }
            }
        }
        
        [DataMember()]
        public String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if ((value != _Name))
                {
                    _Name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        
        [DataMember()]
        public String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                if ((value != _Comment))
                {
                    _Comment = value;
                    OnPropertyChanged("Comment");
                }
            }
        }
        
        [DataMember()]
        public Boolean IsMoney
        {
            get
            {
                return _IsMoney;
            }
            set
            {
                if ((value != _IsMoney))
                {
                    _IsMoney = value;
                    OnPropertyChanged("IsMoney");
                }
            }
        }
        /// <summary>
        /// 是否虚拟卡
        /// </summary>
        [DataMember()]
        public Boolean IsVirtual
        {
            get
            {
                return _IsVirtual;
            }
            set
            {
                if ((value != _IsVirtual))
                {
                    _IsVirtual = value;
                    OnPropertyChanged("IsVirtual");
                }
            }
        }

        [DataMember()]
        public String CardNoRule
        {
            get
            {
                return _CardNoRule;
            }
            set
            {
                if ((value != _CardNoRule))
                {
                    _CardNoRule = value;
                    OnPropertyChanged("CardNoRule");
                }
            }
        }
    }
}
