//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class CardsLog : Entity
    {
        
        private Guid _Id;
        
        private Guid _CardId;
        
        private String _CardNo;
        
        private String _SecondCardNo;
        
        private Guid _Member;
        
        private Guid _CardType;
        
        private Guid _CardLevel;
        
        private Decimal _Balance;
        
        private DateTime _CreateDate;
        
        private Guid _LossUserId;
        
        private DateTime? _LossDate;
        
        private Guid? _LossDeptId;
        
        private Guid _FoundUserId;
        
        private DateTime? _FoundDate;
        
        private Guid? _FoundDeptId;
        
        private DateTime? _AddDate;
        
        private Guid? _AddUserId;
        
        private Guid? _AddDeptId;
        
        private Guid _UserId;
        
        private Guid _DeptId;
        
        private Int32 _Status;
        
        private String _Comment;
        
        private String _AddReason;
        
        private String _CardPwd;
        
        [DataMember()]
        public Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if ((value != _Id))
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public Guid CardId
        {
            get
            {
                return _CardId;
            }
            set
            {
                if ((value != _CardId))
                {
                    _CardId = value;
                    OnPropertyChanged("CardId");
                }
            }
        }
        
        [DataMember()]
        public String CardNo
        {
            get
            {
                return _CardNo;
            }
            set
            {
                if ((value != _CardNo))
                {
                    _CardNo = value;
                    OnPropertyChanged("CardNo");
                }
            }
        }
        
        [DataMember()]
        public String SecondCardNo
        {
            get
            {
                return _SecondCardNo;
            }
            set
            {
                if ((value != _SecondCardNo))
                {
                    _SecondCardNo = value;
                    OnPropertyChanged("SecondCardNo");
                }
            }
        }
        
        [DataMember()]
        public Guid Member
        {
            get
            {
                return _Member;
            }
            set
            {
                if ((value != _Member))
                {
                    _Member = value;
                    OnPropertyChanged("Member");
                }
            }
        }
        
        [DataMember()]
        public Guid CardType
        {
            get
            {
                return _CardType;
            }
            set
            {
                if ((value != _CardType))
                {
                    _CardType = value;
                    OnPropertyChanged("CardType");
                }
            }
        }
        
        [DataMember()]
        public Guid CardLevel
        {
            get
            {
                return _CardLevel;
            }
            set
            {
                if ((value != _CardLevel))
                {
                    _CardLevel = value;
                    OnPropertyChanged("CardLevel");
                }
            }
        }
        
        [DataMember()]
        public Decimal Balance
        {
            get
            {
                return _Balance;
            }
            set
            {
                if ((value != _Balance))
                {
                    _Balance = value;
                    OnPropertyChanged("Balance");
                }
            }
        }
        
        [DataMember()]
        public DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                if ((value != _CreateDate))
                {
                    _CreateDate = value;
                    OnPropertyChanged("CreateDate");
                }
            }
        }
        
        [DataMember()]
        public Guid LossUserId
        {
            get
            {
                return _LossUserId;
            }
            set
            {
                if ((value != _LossUserId))
                {
                    _LossUserId = value;
                    OnPropertyChanged("LossUserId");
                }
            }
        }
        
        [DataMember()]
        public DateTime? LossDate
        {
            get
            {
                return _LossDate;
            }
            set
            {
                if ((value != _LossDate))
                {
                    _LossDate = value;
                    OnPropertyChanged("LossDate");
                }
            }
        }
        
        [DataMember()]
        public Guid? LossDeptId
        {
            get
            {
                return _LossDeptId;
            }
            set
            {
                if ((value != _LossDeptId))
                {
                    _LossDeptId = value;
                    OnPropertyChanged("LossDeptId");
                }
            }
        }
        
        [DataMember()]
        public Guid FoundUserId
        {
            get
            {
                return _FoundUserId;
            }
            set
            {
                if ((value != _FoundUserId))
                {
                    _FoundUserId = value;
                    OnPropertyChanged("FoundUserId");
                }
            }
        }
        
        [DataMember()]
        public DateTime? FoundDate
        {
            get
            {
                return _FoundDate;
            }
            set
            {
                if ((value != _FoundDate))
                {
                    _FoundDate = value;
                    OnPropertyChanged("FoundDate");
                }
            }
        }
        
        [DataMember()]
        public Guid? FoundDeptId
        {
            get
            {
                return _FoundDeptId;
            }
            set
            {
                if ((value != _FoundDeptId))
                {
                    _FoundDeptId = value;
                    OnPropertyChanged("FoundDeptId");
                }
            }
        }
        
        [DataMember()]
        public DateTime? AddDate
        {
            get
            {
                return _AddDate;
            }
            set
            {
                if ((value != _AddDate))
                {
                    _AddDate = value;
                    OnPropertyChanged("AddDate");
                }
            }
        }
        
        [DataMember()]
        public Guid? AddUserId
        {
            get
            {
                return _AddUserId;
            }
            set
            {
                if ((value != _AddUserId))
                {
                    _AddUserId = value;
                    OnPropertyChanged("AddUserId");
                }
            }
        }
        
        [DataMember()]
        public Guid? AddDeptId
        {
            get
            {
                return _AddDeptId;
            }
            set
            {
                if ((value != _AddDeptId))
                {
                    _AddDeptId = value;
                    OnPropertyChanged("AddDeptId");
                }
            }
        }
        
        [DataMember()]
        public Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if ((value != _UserId))
                {
                    _UserId = value;
                    OnPropertyChanged("UserId");
                }
            }
        }
        
        [DataMember()]
        public Guid DeptId
        {
            get
            {
                return _DeptId;
            }
            set
            {
                if ((value != _DeptId))
                {
                    _DeptId = value;
                    OnPropertyChanged("DeptId");
                }
            }
        }
        
        [DataMember()]
        public Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                if ((value != _Status))
                {
                    _Status = value;
                    OnPropertyChanged("Status");
                }
            }
        }
        
        [DataMember()]
        public String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                if ((value != _Comment))
                {
                    _Comment = value;
                    OnPropertyChanged("Comment");
                }
            }
        }
        
        [DataMember()]
        public String AddReason
        {
            get
            {
                return _AddReason;
            }
            set
            {
                if ((value != _AddReason))
                {
                    _AddReason = value;
                    OnPropertyChanged("AddReason");
                }
            }
        }
        
        [DataMember()]
        public String CardPwd
        {
            get
            {
                return _CardPwd;
            }
            set
            {
                if ((value != _CardPwd))
                {
                    _CardPwd = value;
                    OnPropertyChanged("CardPwd");
                }
            }
        }
    }
}
