//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class ConsumePackages : Entity
    {
        
        private Guid _Id;
        
        private Guid _Consume;
        
        private Guid _Inventory;
        
        private Decimal _Price;
        
        private Decimal _Quantity;
        
        private Decimal _Amount;
        
        private DateTime _CreateDate;
        
        private Guid _UserId;
        
        private Guid _DeptId;
        
        private Decimal _Sum;
        
        private Decimal _Discount;
        
        [DataMember()]
        public Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if ((value != _Id))
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public Guid Consume
        {
            get
            {
                return _Consume;
            }
            set
            {
                if ((value != _Consume))
                {
                    _Consume = value;
                    OnPropertyChanged("Consume");
                }
            }
        }
        
        [DataMember()]
        public Guid Inventory
        {
            get
            {
                return _Inventory;
            }
            set
            {
                if ((value != _Inventory))
                {
                    _Inventory = value;
                    OnPropertyChanged("Inventory");
                }
            }
        }
        
        [DataMember()]
        public Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                if ((value != _Price))
                {
                    _Price = value;
                    OnPropertyChanged("Price");
                }
            }
        }
        
        [DataMember()]
        public Decimal Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                if ((value != _Quantity))
                {
                    _Quantity = value;
                    OnPropertyChanged("Quantity");
                }
            }
        }
        
        [DataMember()]
        public Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                if ((value != _Amount))
                {
                    _Amount = value;
                    OnPropertyChanged("Amount");
                }
            }
        }
        
        [DataMember()]
        public DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                if ((value != _CreateDate))
                {
                    _CreateDate = value;
                    OnPropertyChanged("CreateDate");
                }
            }
        }
        
        [DataMember()]
        public Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if ((value != _UserId))
                {
                    _UserId = value;
                    OnPropertyChanged("UserId");
                }
            }
        }
        
        [DataMember()]
        public Guid DeptId
        {
            get
            {
                return _DeptId;
            }
            set
            {
                if ((value != _DeptId))
                {
                    _DeptId = value;
                    OnPropertyChanged("DeptId");
                }
            }
        }
        
        [DataMember()]
        public Decimal Sum
        {
            get
            {
                return _Sum;
            }
            set
            {
                if ((value != _Sum))
                {
                    _Sum = value;
                    OnPropertyChanged("Sum");
                }
            }
        }
        
        [DataMember()]
        public Decimal Discount
        {
            get
            {
                return _Discount;
            }
            set
            {
                if ((value != _Discount))
                {
                    _Discount = value;
                    OnPropertyChanged("Discount");
                }
            }
        }
    }
}
