//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class ConsumeDonateInv : Entity
    {
        
        private Guid _Id;
        
        private Guid _Consume;
        
        private Guid _Inventory;
        
        [DataMember()]
        public Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if ((value != _Id))
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public Guid Consume
        {
            get
            {
                return _Consume;
            }
            set
            {
                if ((value != _Consume))
                {
                    _Consume = value;
                    OnPropertyChanged("Consume");
                }
            }
        }
        
        [DataMember()]
        public Guid Inventory
        {
            get
            {
                return _Inventory;
            }
            set
            {
                if ((value != _Inventory))
                {
                    _Inventory = value;
                    OnPropertyChanged("Inventory");
                }
            }
        }
    }
}
