//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class EnumTypeDescription : Entity
    {
        
        private String _Code;
        
        private Int32 _Value;
        
        private String _Description;
        
        [DataMember()]
        public String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if ((value != _Code))
                {
                    _Code = value;
                    OnPropertyChanged("Code");
                }
            }
        }
        
        [DataMember()]
        public Int32 Value
        {
            get
            {
                return _Value;
            }
            set
            {
                if ((value != _Value))
                {
                    _Value = value;
                    OnPropertyChanged("Value");
                }
            }
        }
        
        [DataMember()]
        public String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                if ((value != _Description))
                {
                    _Description = value;
                    OnPropertyChanged("Description");
                }
            }
        }
    }
}
