//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class InventoryDeptPrice : Entity
    {
        
        private Guid _DeptId;
        
        private Guid _InvId;
        
        private Decimal _SalePrice;
        
        private Decimal _SalePrice0;
        
        private Decimal _SalePrice1;
        
        private Decimal _SalePrice2;
        
        private Decimal _SalePoint;
        
        private Decimal _SalePoint0;
        
        private Decimal _SalePoint1;
        
        private Decimal _SalePoint2;
        
        [DataMember()]
        public Guid DeptId
        {
            get
            {
                return _DeptId;
            }
            set
            {
                if ((value != _DeptId))
                {
                    _DeptId = value;
                    OnPropertyChanged("DeptId");
                }
            }
        }
        
        [DataMember()]
        public Guid InvId
        {
            get
            {
                return _InvId;
            }
            set
            {
                if ((value != _InvId))
                {
                    _InvId = value;
                    OnPropertyChanged("InvId");
                }
            }
        }
        
        [DataMember()]
        public Decimal SalePrice
        {
            get
            {
                return _SalePrice;
            }
            set
            {
                if ((value != _SalePrice))
                {
                    _SalePrice = value;
                    OnPropertyChanged("SalePrice");
                }
            }
        }
        
        [DataMember()]
        public Decimal SalePrice0
        {
            get
            {
                return _SalePrice0;
            }
            set
            {
                if ((value != _SalePrice0))
                {
                    _SalePrice0 = value;
                    OnPropertyChanged("SalePrice0");
                }
            }
        }
        
        [DataMember()]
        public Decimal SalePrice1
        {
            get
            {
                return _SalePrice1;
            }
            set
            {
                if ((value != _SalePrice1))
                {
                    _SalePrice1 = value;
                    OnPropertyChanged("SalePrice1");
                }
            }
        }
        
        [DataMember()]
        public Decimal SalePrice2
        {
            get
            {
                return _SalePrice2;
            }
            set
            {
                if ((value != _SalePrice2))
                {
                    _SalePrice2 = value;
                    OnPropertyChanged("SalePrice2");
                }
            }
        }
        
        [DataMember()]
        public Decimal SalePoint
        {
            get
            {
                return _SalePoint;
            }
            set
            {
                if ((value != _SalePoint))
                {
                    _SalePoint = value;
                    OnPropertyChanged("SalePoint");
                }
            }
        }
        
        [DataMember()]
        public Decimal SalePoint0
        {
            get
            {
                return _SalePoint0;
            }
            set
            {
                if ((value != _SalePoint0))
                {
                    _SalePoint0 = value;
                    OnPropertyChanged("SalePoint0");
                }
            }
        }
        
        [DataMember()]
        public Decimal SalePoint1
        {
            get
            {
                return _SalePoint1;
            }
            set
            {
                if ((value != _SalePoint1))
                {
                    _SalePoint1 = value;
                    OnPropertyChanged("SalePoint1");
                }
            }
        }
        
        [DataMember()]
        public Decimal SalePoint2
        {
            get
            {
                return _SalePoint2;
            }
            set
            {
                if ((value != _SalePoint2))
                {
                    _SalePoint2 = value;
                    OnPropertyChanged("SalePoint2");
                }
            }
        }
    }
}
