//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class InvPrice : Entity
    {
        
        private Guid _Id;
        
        private String _Code;
        
        private String _Name;
        
        private Guid _InvId;
        
        private Decimal _SalePrice;
        
        private Decimal _SalePoint;

        private Boolean _IsInvalid;

        private String _Comment;
        
        [DataMember()]
        public Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if ((value != _Id))
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if ((value != _Code))
                {
                    _Code = value;
                    OnPropertyChanged("Code");
                }
            }
        }
        
        [DataMember()]
        public String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if ((value != _Name))
                {
                    _Name = value;
                    OnPropertyChanged("Name");
                }
            }
        }

        [DataMember()]
        public Guid InvId
        {
            get
            {
                return _InvId;
            }
            set
            {
                if ((value != _InvId))
                {
                    _InvId = value;
                    OnPropertyChanged("InvId");
                }
            }
        }
        
        [DataMember()]
        public Decimal SalePrice
        {
            get
            {
                return _SalePrice;
            }
            set
            {
                if ((value != _SalePrice))
                {
                    _SalePrice = value;
                    OnPropertyChanged("SalePrice");
                }
            }
        }
        
        [DataMember()]
        public Decimal SalePoint
        {
            get
            {
                return _SalePoint;
            }
            set
            {
                if ((value != _SalePoint))
                {
                    _SalePoint = value;
                    OnPropertyChanged("SalePoint");
                }
            }
        }
        
        [DataMember()]
        public Boolean IsInvalid
        {
            get
            {
                return _IsInvalid;
            }
            set
            {
                if ((value != _IsInvalid))
                {
                    _IsInvalid = value;
                    OnPropertyChanged("IsInvalid");
                }
            }
        }

        [DataMember()]
        public String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                if ((value != _Comment))
                {
                    _Comment = value;
                    OnPropertyChanged("Comment");
                }
            }
        }
        
    }
}
