//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class MixVouch : Entity
    {
        
        private Guid _Id;
        
        private String _Code;
        
        private DateTime _MVDate;
        
        private Guid _OutDeptId;
        
        private Guid _OutWhId;
        
        private Guid _InDeptId;
        
        private Guid _InWhId;
        
        private Guid _Salesman;
        
        private String _Memo;
        
        private Guid _Maker;
        
        private DateTime _MakeDate;
        
        private DateTime _MakeTime;
        
        private Boolean _IsVerify;
        
        private Guid? _Verifier;
        
        private DateTime? _VerifyDate;
        
        private DateTime? _VerifyTime;
        
        private Guid? _Modifier;
        
        private DateTime? _ModifyDate;
        
        private DateTime? _ModifyTime;
        
        [DataMember()]
        public Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if ((value != _Id))
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if ((value != _Code))
                {
                    _Code = value;
                    OnPropertyChanged("Code");
                }
            }
        }
        
        [DataMember()]
        public DateTime MVDate
        {
            get
            {
                return _MVDate;
            }
            set
            {
                if ((value != _MVDate))
                {
                    _MVDate = value;
                    OnPropertyChanged("MVDate");
                }
            }
        }
        
        [DataMember()]
        public Guid OutDeptId
        {
            get
            {
                return _OutDeptId;
            }
            set
            {
                if ((value != _OutDeptId))
                {
                    _OutDeptId = value;
                    OnPropertyChanged("OutDeptId");
                }
            }
        }
        
        [DataMember()]
        public Guid OutWhId
        {
            get
            {
                return _OutWhId;
            }
            set
            {
                if ((value != _OutWhId))
                {
                    _OutWhId = value;
                    OnPropertyChanged("OutWhId");
                }
            }
        }
        
        [DataMember()]
        public Guid InDeptId
        {
            get
            {
                return _InDeptId;
            }
            set
            {
                if ((value != _InDeptId))
                {
                    _InDeptId = value;
                    OnPropertyChanged("InDeptId");
                }
            }
        }
        
        [DataMember()]
        public Guid InWhId
        {
            get
            {
                return _InWhId;
            }
            set
            {
                if ((value != _InWhId))
                {
                    _InWhId = value;
                    OnPropertyChanged("InWhId");
                }
            }
        }
        
        [DataMember()]
        public Guid Salesman
        {
            get
            {
                return _Salesman;
            }
            set
            {
                if ((value != _Salesman))
                {
                    _Salesman = value;
                    OnPropertyChanged("Salesman");
                }
            }
        }
        
        [DataMember()]
        public String Memo
        {
            get
            {
                return _Memo;
            }
            set
            {
                if ((value != _Memo))
                {
                    _Memo = value;
                    OnPropertyChanged("Memo");
                }
            }
        }
        
        [DataMember()]
        public Guid Maker
        {
            get
            {
                return _Maker;
            }
            set
            {
                if ((value != _Maker))
                {
                    _Maker = value;
                    OnPropertyChanged("Maker");
                }
            }
        }
        
        [DataMember()]
        public DateTime MakeDate
        {
            get
            {
                return _MakeDate;
            }
            set
            {
                if ((value != _MakeDate))
                {
                    _MakeDate = value;
                    OnPropertyChanged("MakeDate");
                }
            }
        }
        
        [DataMember()]
        public DateTime MakeTime
        {
            get
            {
                return _MakeTime;
            }
            set
            {
                if ((value != _MakeTime))
                {
                    _MakeTime = value;
                    OnPropertyChanged("MakeTime");
                }
            }
        }
        
        [DataMember()]
        public Boolean IsVerify
        {
            get
            {
                return _IsVerify;
            }
            set
            {
                if ((value != _IsVerify))
                {
                    _IsVerify = value;
                    OnPropertyChanged("IsVerify");
                }
            }
        }
        
        [DataMember()]
        public Guid? Verifier
        {
            get
            {
                return _Verifier;
            }
            set
            {
                if ((value != _Verifier))
                {
                    _Verifier = value;
                    OnPropertyChanged("Verifier");
                }
            }
        }
        
        [DataMember()]
        public DateTime? VerifyDate
        {
            get
            {
                return _VerifyDate;
            }
            set
            {
                if ((value != _VerifyDate))
                {
                    _VerifyDate = value;
                    OnPropertyChanged("VerifyDate");
                }
            }
        }
        
        [DataMember()]
        public DateTime? VerifyTime
        {
            get
            {
                return _VerifyTime;
            }
            set
            {
                if ((value != _VerifyTime))
                {
                    _VerifyTime = value;
                    OnPropertyChanged("VerifyTime");
                }
            }
        }
        
        [DataMember()]
        public Guid? Modifier
        {
            get
            {
                return _Modifier;
            }
            set
            {
                if ((value != _Modifier))
                {
                    _Modifier = value;
                    OnPropertyChanged("Modifier");
                }
            }
        }
        
        [DataMember()]
        public DateTime? ModifyDate
        {
            get
            {
                return _ModifyDate;
            }
            set
            {
                if ((value != _ModifyDate))
                {
                    _ModifyDate = value;
                    OnPropertyChanged("ModifyDate");
                }
            }
        }
        
        [DataMember()]
        public DateTime? ModifyTime
        {
            get
            {
                return _ModifyTime;
            }
            set
            {
                if ((value != _ModifyTime))
                {
                    _ModifyTime = value;
                    OnPropertyChanged("ModifyTime");
                }
            }
        }
    }
}
