//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class OrderMenusHis : Entity
    {
        
        private Guid _Id;
        
        private Guid _LinkId;
        
        private Guid _OrderId;
        
        private Guid _InventoryId;
        
        private Decimal _Price;
        
        private Decimal _Quantity;
        
        private Decimal _Amount;
        
        private Guid _UserId;
        
        private DateTime _CreateDate;
        
        private String _Comment;
        
        private Int32 _Status;
        
        private Guid? _BackUserId;
        
        private DateTime? _BackCreateDate;
        
        private Decimal _BackQuantity;
        
        private String _BackReseaon;
        
        private Guid? _OrderUserId;
        
        private DateTime? _OrderCreateDate;
        
        private Guid? _MissUserId;
        
        private DateTime? _MissCreateDate;
        
        private Guid? _HurryUserId;
        
        private DateTime? _HurryCreateDate;
        
        private Guid? _BillUserId;
        
        private DateTime? _BillCreateDate;
        
        private Guid? _MenuUserId;
        
        private DateTime? _MenuCreateDate;
        
        private Decimal _MenuQuantity;
        
        private Guid? _Oper;
        
        private DateTime? _OperDate;
        
        private Decimal _BillQuantity;
        
        private Decimal _MissQuantity;
        
        private Boolean _IsPackage;
        
        private Guid? _PackageId;
        
        [DataMember()]
        public Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if ((value != _Id))
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public Guid LinkId
        {
            get
            {
                return _LinkId;
            }
            set
            {
                if ((value != _LinkId))
                {
                    _LinkId = value;
                    OnPropertyChanged("LinkId");
                }
            }
        }
        
        [DataMember()]
        public Guid OrderId
        {
            get
            {
                return _OrderId;
            }
            set
            {
                if ((value != _OrderId))
                {
                    _OrderId = value;
                    OnPropertyChanged("OrderId");
                }
            }
        }
        
        [DataMember()]
        public Guid InventoryId
        {
            get
            {
                return _InventoryId;
            }
            set
            {
                if ((value != _InventoryId))
                {
                    _InventoryId = value;
                    OnPropertyChanged("InventoryId");
                }
            }
        }
        
        [DataMember()]
        public Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                if ((value != _Price))
                {
                    _Price = value;
                    OnPropertyChanged("Price");
                }
            }
        }
        
        [DataMember()]
        public Decimal Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                if ((value != _Quantity))
                {
                    _Quantity = value;
                    OnPropertyChanged("Quantity");
                }
            }
        }
        
        [DataMember()]
        public Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                if ((value != _Amount))
                {
                    _Amount = value;
                    OnPropertyChanged("Amount");
                }
            }
        }
        
        [DataMember()]
        public Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if ((value != _UserId))
                {
                    _UserId = value;
                    OnPropertyChanged("UserId");
                }
            }
        }
        
        [DataMember()]
        public DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                if ((value != _CreateDate))
                {
                    _CreateDate = value;
                    OnPropertyChanged("CreateDate");
                }
            }
        }
        
        [DataMember()]
        public String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                if ((value != _Comment))
                {
                    _Comment = value;
                    OnPropertyChanged("Comment");
                }
            }
        }
        
        [DataMember()]
        public Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                if ((value != _Status))
                {
                    _Status = value;
                    OnPropertyChanged("Status");
                }
            }
        }
        
        [DataMember()]
        public Guid? BackUserId
        {
            get
            {
                return _BackUserId;
            }
            set
            {
                if ((value != _BackUserId))
                {
                    _BackUserId = value;
                    OnPropertyChanged("BackUserId");
                }
            }
        }
        
        [DataMember()]
        public DateTime? BackCreateDate
        {
            get
            {
                return _BackCreateDate;
            }
            set
            {
                if ((value != _BackCreateDate))
                {
                    _BackCreateDate = value;
                    OnPropertyChanged("BackCreateDate");
                }
            }
        }
        
        [DataMember()]
        public Decimal BackQuantity
        {
            get
            {
                return _BackQuantity;
            }
            set
            {
                if ((value != _BackQuantity))
                {
                    _BackQuantity = value;
                    OnPropertyChanged("BackQuantity");
                }
            }
        }
        
        [DataMember()]
        public String BackReseaon
        {
            get
            {
                return _BackReseaon;
            }
            set
            {
                if ((value != _BackReseaon))
                {
                    _BackReseaon = value;
                    OnPropertyChanged("BackReseaon");
                }
            }
        }
        
        [DataMember()]
        public Guid? OrderUserId
        {
            get
            {
                return _OrderUserId;
            }
            set
            {
                if ((value != _OrderUserId))
                {
                    _OrderUserId = value;
                    OnPropertyChanged("OrderUserId");
                }
            }
        }
        
        [DataMember()]
        public DateTime? OrderCreateDate
        {
            get
            {
                return _OrderCreateDate;
            }
            set
            {
                if ((value != _OrderCreateDate))
                {
                    _OrderCreateDate = value;
                    OnPropertyChanged("OrderCreateDate");
                }
            }
        }
        
        [DataMember()]
        public Guid? MissUserId
        {
            get
            {
                return _MissUserId;
            }
            set
            {
                if ((value != _MissUserId))
                {
                    _MissUserId = value;
                    OnPropertyChanged("MissUserId");
                }
            }
        }
        
        [DataMember()]
        public DateTime? MissCreateDate
        {
            get
            {
                return _MissCreateDate;
            }
            set
            {
                if ((value != _MissCreateDate))
                {
                    _MissCreateDate = value;
                    OnPropertyChanged("MissCreateDate");
                }
            }
        }
        
        [DataMember()]
        public Guid? HurryUserId
        {
            get
            {
                return _HurryUserId;
            }
            set
            {
                if ((value != _HurryUserId))
                {
                    _HurryUserId = value;
                    OnPropertyChanged("HurryUserId");
                }
            }
        }
        
        [DataMember()]
        public DateTime? HurryCreateDate
        {
            get
            {
                return _HurryCreateDate;
            }
            set
            {
                if ((value != _HurryCreateDate))
                {
                    _HurryCreateDate = value;
                    OnPropertyChanged("HurryCreateDate");
                }
            }
        }
        
        [DataMember()]
        public Guid? BillUserId
        {
            get
            {
                return _BillUserId;
            }
            set
            {
                if ((value != _BillUserId))
                {
                    _BillUserId = value;
                    OnPropertyChanged("BillUserId");
                }
            }
        }
        
        [DataMember()]
        public DateTime? BillCreateDate
        {
            get
            {
                return _BillCreateDate;
            }
            set
            {
                if ((value != _BillCreateDate))
                {
                    _BillCreateDate = value;
                    OnPropertyChanged("BillCreateDate");
                }
            }
        }
        
        [DataMember()]
        public Guid? MenuUserId
        {
            get
            {
                return _MenuUserId;
            }
            set
            {
                if ((value != _MenuUserId))
                {
                    _MenuUserId = value;
                    OnPropertyChanged("MenuUserId");
                }
            }
        }
        
        [DataMember()]
        public DateTime? MenuCreateDate
        {
            get
            {
                return _MenuCreateDate;
            }
            set
            {
                if ((value != _MenuCreateDate))
                {
                    _MenuCreateDate = value;
                    OnPropertyChanged("MenuCreateDate");
                }
            }
        }
        
        [DataMember()]
        public Decimal MenuQuantity
        {
            get
            {
                return _MenuQuantity;
            }
            set
            {
                if ((value != _MenuQuantity))
                {
                    _MenuQuantity = value;
                    OnPropertyChanged("MenuQuantity");
                }
            }
        }
        
        [DataMember()]
        public Guid? Oper
        {
            get
            {
                return _Oper;
            }
            set
            {
                if ((value != _Oper))
                {
                    _Oper = value;
                    OnPropertyChanged("Oper");
                }
            }
        }
        
        [DataMember()]
        public DateTime? OperDate
        {
            get
            {
                return _OperDate;
            }
            set
            {
                if ((value != _OperDate))
                {
                    _OperDate = value;
                    OnPropertyChanged("OperDate");
                }
            }
        }
        
        [DataMember()]
        public Decimal BillQuantity
        {
            get
            {
                return _BillQuantity;
            }
            set
            {
                if ((value != _BillQuantity))
                {
                    _BillQuantity = value;
                    OnPropertyChanged("BillQuantity");
                }
            }
        }
        
        [DataMember()]
        public Decimal MissQuantity
        {
            get
            {
                return _MissQuantity;
            }
            set
            {
                if ((value != _MissQuantity))
                {
                    _MissQuantity = value;
                    OnPropertyChanged("MissQuantity");
                }
            }
        }
        
        [DataMember()]
        public Boolean IsPackage
        {
            get
            {
                return _IsPackage;
            }
            set
            {
                if ((value != _IsPackage))
                {
                    _IsPackage = value;
                    OnPropertyChanged("IsPackage");
                }
            }
        }
        
        [DataMember()]
        public Guid? PackageId
        {
            get
            {
                return _PackageId;
            }
            set
            {
                if ((value != _PackageId))
                {
                    _PackageId = value;
                    OnPropertyChanged("PackageId");
                }
            }
        }
    }
}
