//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class Packages : Entity
    {
        
        private Guid _Id;
        
        private Guid _PackageId;
        
        private Guid _InventoryId;
        
        private Decimal _Price;
        
        private Boolean _IsOptional;
        
        private String _OptionalGroup;
        
        private String _Comment;
        
        [DataMember()]
        public Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if ((value != _Id))
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public Guid PackageId
        {
            get
            {
                return _PackageId;
            }
            set
            {
                if ((value != _PackageId))
                {
                    _PackageId = value;
                    OnPropertyChanged("PackageId");
                }
            }
        }
        
        [DataMember()]
        public Guid InventoryId
        {
            get
            {
                return _InventoryId;
            }
            set
            {
                if ((value != _InventoryId))
                {
                    _InventoryId = value;
                    OnPropertyChanged("InventoryId");
                }
            }
        }
        
        [DataMember()]
        public Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                if ((value != _Price))
                {
                    _Price = value;
                    OnPropertyChanged("Price");
                }
            }
        }
        
        [DataMember()]
        public Boolean IsOptional
        {
            get
            {
                return _IsOptional;
            }
            set
            {
                if ((value != _IsOptional))
                {
                    _IsOptional = value;
                    OnPropertyChanged("IsOptional");
                }
            }
        }
        
        [DataMember()]
        public String OptionalGroup
        {
            get
            {
                return _OptionalGroup;
            }
            set
            {
                if ((value != _OptionalGroup))
                {
                    _OptionalGroup = value;
                    OnPropertyChanged("OptionalGroup");
                }
            }
        }
        
        [DataMember()]
        public String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                if ((value != _Comment))
                {
                    _Comment = value;
                    OnPropertyChanged("Comment");
                }
            }
        }
    }
}
