//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class PlayLists : Entity
    {
        
        private Guid _Id;
        
        private Guid? _DeptId;
        
        private String _Code;
        
        private String _Name;
        
        private TimeSpan _BeginTime;
        
        private TimeSpan _EndTime;
        
        private Boolean _IsEnabled;
        
        [DataMember()]
        public Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if ((value != _Id))
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public Guid? DeptId
        {
            get
            {
                return _DeptId;
            }
            set
            {
                if ((value != _DeptId))
                {
                    _DeptId = value;
                    OnPropertyChanged("DeptId");
                }
            }
        }
        
        [DataMember()]
        public String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if ((value != _Code))
                {
                    _Code = value;
                    OnPropertyChanged("Code");
                }
            }
        }
        
        [DataMember()]
        public String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if ((value != _Name))
                {
                    _Name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        
        [DataMember()]
        public TimeSpan BeginTime
        {
            get
            {
                return _BeginTime;
            }
            set
            {
                if ((value != _BeginTime))
                {
                    _BeginTime = value;
                    OnPropertyChanged("BeginTime");
                }
            }
        }
        
        [DataMember()]
        public TimeSpan EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                if ((value != _EndTime))
                {
                    _EndTime = value;
                    OnPropertyChanged("EndTime");
                }
            }
        }
        
        [DataMember()]
        public Boolean IsEnabled
        {
            get
            {
                return _IsEnabled;
            }
            set
            {
                if ((value != _IsEnabled))
                {
                    _IsEnabled = value;
                    OnPropertyChanged("IsEnabled");
                }
            }
        }
    }
}
