//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class RdRecords : Entity
    {
        
        private Guid _Id;
        
        private Guid _RdId;
        
        private Guid _InvId;
        
        private Guid _MainUnit;
        
        private Guid _STUnit;
        
        private Decimal _ExchRate;
        
        private Decimal _LastBanaceQuantity;
        
        private Decimal _LastBalanceLocatorQuantity;
        
        private Decimal _Quantity;
        
        private Decimal _BalanceQuantity;
        
        private Decimal _BalanceLocatorQuantity;
        
        private Decimal _LastBalanceNum;
        
        private Decimal _LastBalanceLocatorNum;
        
        private Decimal _Num;
        
        private Decimal _BalanceNum;
        
        private Decimal _BalanceLocatorNum;
        
        private Decimal _Price;
        
        private Decimal _LastBalanceAmount;
        
        private Decimal _LastBalanceLocatorAmount;
        
        private Decimal _Amount;
        
        private Decimal _BalanceAmount;
        
        private Decimal _BalanceLocatorAmount;
        
        private String _Batch;
        
        private DateTime? _MadeDate;
        
        private Int32? _ShelfLife;
        
        private Int32? _ShelfLifeType;
        
        private DateTime? _InvalidDate;
        
        private Guid? _Locator;
        
        private Decimal _DueQuantity;
        
        private Decimal _DueNum;
        
        private Decimal _DueAmount;
        
        private String _Memo;

        private Guid? _SourceId;
        [DataMember()]
        public Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if ((value != _Id))
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public Guid RdId
        {
            get
            {
                return _RdId;
            }
            set
            {
                if ((value != _RdId))
                {
                    _RdId = value;
                    OnPropertyChanged("RdId");
                }
            }
        }
        
        [DataMember()]
        public Guid InvId
        {
            get
            {
                return _InvId;
            }
            set
            {
                if ((value != _InvId))
                {
                    _InvId = value;
                    OnPropertyChanged("InvId");
                }
            }
        }
        
        [DataMember()]
        public Guid MainUnit
        {
            get
            {
                return _MainUnit;
            }
            set
            {
                if ((value != _MainUnit))
                {
                    _MainUnit = value;
                    OnPropertyChanged("MainUnit");
                }
            }
        }
        
        [DataMember()]
        public Guid STUnit
        {
            get
            {
                return _STUnit;
            }
            set
            {
                if ((value != _STUnit))
                {
                    _STUnit = value;
                    OnPropertyChanged("STUnit");
                }
            }
        }
        
        [DataMember()]
        public Decimal ExchRate
        {
            get
            {
                return _ExchRate;
            }
            set
            {
                if ((value != _ExchRate))
                {
                    _ExchRate = value;
                    OnPropertyChanged("ExchRate");
                }
            }
        }
        
        [DataMember()]
        public Decimal LastBanaceQuantity
        {
            get
            {
                return _LastBanaceQuantity;
            }
            set
            {
                if ((value != _LastBanaceQuantity))
                {
                    _LastBanaceQuantity = value;
                    OnPropertyChanged("LastBanaceQuantity");
                }
            }
        }
        
        [DataMember()]
        public Decimal LastBalanceLocatorQuantity
        {
            get
            {
                return _LastBalanceLocatorQuantity;
            }
            set
            {
                if ((value != _LastBalanceLocatorQuantity))
                {
                    _LastBalanceLocatorQuantity = value;
                    OnPropertyChanged("LastBalanceLocatorQuantity");
                }
            }
        }
        
        [DataMember()]
        public Decimal Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                if ((value != _Quantity))
                {
                    _Quantity = value;
                    OnPropertyChanged("Quantity");
                }
            }
        }
        
        [DataMember()]
        public Decimal BalanceQuantity
        {
            get
            {
                return _BalanceQuantity;
            }
            set
            {
                if ((value != _BalanceQuantity))
                {
                    _BalanceQuantity = value;
                    OnPropertyChanged("BalanceQuantity");
                }
            }
        }
        
        [DataMember()]
        public Decimal BalanceLocatorQuantity
        {
            get
            {
                return _BalanceLocatorQuantity;
            }
            set
            {
                if ((value != _BalanceLocatorQuantity))
                {
                    _BalanceLocatorQuantity = value;
                    OnPropertyChanged("BalanceLocatorQuantity");
                }
            }
        }
        
        [DataMember()]
        public Decimal LastBalanceNum
        {
            get
            {
                return _LastBalanceNum;
            }
            set
            {
                if ((value != _LastBalanceNum))
                {
                    _LastBalanceNum = value;
                    OnPropertyChanged("LastBalanceNum");
                }
            }
        }
        
        [DataMember()]
        public Decimal LastBalanceLocatorNum
        {
            get
            {
                return _LastBalanceLocatorNum;
            }
            set
            {
                if ((value != _LastBalanceLocatorNum))
                {
                    _LastBalanceLocatorNum = value;
                    OnPropertyChanged("LastBalanceLocatorNum");
                }
            }
        }
        
        [DataMember()]
        public Decimal Num
        {
            get
            {
                return _Num;
            }
            set
            {
                if ((value != _Num))
                {
                    _Num = value;
                    OnPropertyChanged("Num");
                }
            }
        }
        
        [DataMember()]
        public Decimal BalanceNum
        {
            get
            {
                return _BalanceNum;
            }
            set
            {
                if ((value != _BalanceNum))
                {
                    _BalanceNum = value;
                    OnPropertyChanged("BalanceNum");
                }
            }
        }
        
        [DataMember()]
        public Decimal BalanceLocatorNum
        {
            get
            {
                return _BalanceLocatorNum;
            }
            set
            {
                if ((value != _BalanceLocatorNum))
                {
                    _BalanceLocatorNum = value;
                    OnPropertyChanged("BalanceLocatorNum");
                }
            }
        }
        
        [DataMember()]
        public Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                if ((value != _Price))
                {
                    _Price = value;
                    OnPropertyChanged("Price");
                }
            }
        }
        
        [DataMember()]
        public Decimal LastBalanceAmount
        {
            get
            {
                return _LastBalanceAmount;
            }
            set
            {
                if ((value != _LastBalanceAmount))
                {
                    _LastBalanceAmount = value;
                    OnPropertyChanged("LastBalanceAmount");
                }
            }
        }
        
        [DataMember()]
        public Decimal LastBalanceLocatorAmount
        {
            get
            {
                return _LastBalanceLocatorAmount;
            }
            set
            {
                if ((value != _LastBalanceLocatorAmount))
                {
                    _LastBalanceLocatorAmount = value;
                    OnPropertyChanged("LastBalanceLocatorAmount");
                }
            }
        }
        
        [DataMember()]
        public Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                if ((value != _Amount))
                {
                    _Amount = value;
                    OnPropertyChanged("Amount");
                }
            }
        }
        
        [DataMember()]
        public Decimal BalanceAmount
        {
            get
            {
                return _BalanceAmount;
            }
            set
            {
                if ((value != _BalanceAmount))
                {
                    _BalanceAmount = value;
                    OnPropertyChanged("BalanceAmount");
                }
            }
        }
        
        [DataMember()]
        public Decimal BalanceLocatorAmount
        {
            get
            {
                return _BalanceLocatorAmount;
            }
            set
            {
                if ((value != _BalanceLocatorAmount))
                {
                    _BalanceLocatorAmount = value;
                    OnPropertyChanged("BalanceLocatorAmount");
                }
            }
        }
        
        [DataMember()]
        public String Batch
        {
            get
            {
                return _Batch;
            }
            set
            {
                if ((value != _Batch))
                {
                    _Batch = value;
                    OnPropertyChanged("Batch");
                }
            }
        }
        
        [DataMember()]
        public DateTime? MadeDate
        {
            get
            {
                return _MadeDate;
            }
            set
            {
                if ((value != _MadeDate))
                {
                    _MadeDate = value;
                    OnPropertyChanged("MadeDate");
                }
            }
        }
        
        [DataMember()]
        public Int32? ShelfLife
        {
            get
            {
                return _ShelfLife;
            }
            set
            {
                if ((value != _ShelfLife))
                {
                    _ShelfLife = value;
                    OnPropertyChanged("ShelfLife");
                }
            }
        }
        
        [DataMember()]
        public Int32? ShelfLifeType
        {
            get
            {
                return _ShelfLifeType;
            }
            set
            {
                if ((value != _ShelfLifeType))
                {
                    _ShelfLifeType = value;
                    OnPropertyChanged("ShelfLifeType");
                }
            }
        }
        
        [DataMember()]
        public DateTime? InvalidDate
        {
            get
            {
                return _InvalidDate;
            }
            set
            {
                if ((value != _InvalidDate))
                {
                    _InvalidDate = value;
                    OnPropertyChanged("InvalidDate");
                }
            }
        }
        
        [DataMember()]
        public Guid? Locator
        {
            get
            {
                return _Locator;
            }
            set
            {
                if ((value != _Locator))
                {
                    _Locator = value;
                    OnPropertyChanged("Locator");
                }
            }
        }
        
        [DataMember()]
        public Decimal DueQuantity
        {
            get
            {
                return _DueQuantity;
            }
            set
            {
                if ((value != _DueQuantity))
                {
                    _DueQuantity = value;
                    OnPropertyChanged("DueQuantity");
                }
            }
        }
        
        [DataMember()]
        public Decimal DueNum
        {
            get
            {
                return _DueNum;
            }
            set
            {
                if ((value != _DueNum))
                {
                    _DueNum = value;
                    OnPropertyChanged("DueNum");
                }
            }
        }
        
        [DataMember()]
        public Decimal DueAmount
        {
            get
            {
                return _DueAmount;
            }
            set
            {
                if ((value != _DueAmount))
                {
                    _DueAmount = value;
                    OnPropertyChanged("DueAmount");
                }
            }
        }
        
        [DataMember()]
        public String Memo
        {
            get
            {
                return _Memo;
            }
            set
            {
                if ((value != _Memo))
                {
                    _Memo = value;
                    OnPropertyChanged("Memo");
                }
            }
        }

        [DataMember()]
        public Guid? SourceId
        {
            get
            {
                return _SourceId;
            }
            set
            {
                if ((value != _SourceId))
                {
                    _SourceId = value;
                    OnPropertyChanged("SourceId");
                }
            }
        }
    }
}
