//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class schema_info : Entity
    {
        
        private Int32 _schema_major_version;
        
        private Int32 _schema_minor_version;
        
        private String _schema_extended_info;
        
        [DataMember()]
        public Int32 schema_major_version
        {
            get
            {
                return _schema_major_version;
            }
            set
            {
                if ((value != _schema_major_version))
                {
                    _schema_major_version = value;
                    OnPropertyChanged("schema_major_version");
                }
            }
        }
        
        [DataMember()]
        public Int32 schema_minor_version
        {
            get
            {
                return _schema_minor_version;
            }
            set
            {
                if ((value != _schema_minor_version))
                {
                    _schema_minor_version = value;
                    OnPropertyChanged("schema_minor_version");
                }
            }
        }
        
        [DataMember()]
        public String schema_extended_info
        {
            get
            {
                return _schema_extended_info;
            }
            set
            {
                if ((value != _schema_extended_info))
                {
                    _schema_extended_info = value;
                    OnPropertyChanged("schema_extended_info");
                }
            }
        }
    }
}
