//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class Vendor : Entity
    {
        
        private Guid _Id;
        
        private String _Code;
        
        private String _Name;
        
        private String _Tel;
        
        private String _Fax;
        
        private String _Phone;
        
        private String _Zip;
        
        private String _Linkman;
        
        private String _Address;
        
        private String _Email;

        private Int32 _VendorType;
        [DataMember()]
        public Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if ((value != _Id))
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        
        [DataMember()]
        public String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if ((value != _Code))
                {
                    _Code = value;
                    OnPropertyChanged("Code");
                }
            }
        }
        
        [DataMember()]
        public String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if ((value != _Name))
                {
                    _Name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        
        [DataMember()]
        public String Tel
        {
            get
            {
                return _Tel;
            }
            set
            {
                if ((value != _Tel))
                {
                    _Tel = value;
                    OnPropertyChanged("Tel");
                }
            }
        }
        
        [DataMember()]
        public String Fax
        {
            get
            {
                return _Fax;
            }
            set
            {
                if ((value != _Fax))
                {
                    _Fax = value;
                    OnPropertyChanged("Fax");
                }
            }
        }
        
        [DataMember()]
        public String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                if ((value != _Phone))
                {
                    _Phone = value;
                    OnPropertyChanged("Phone");
                }
            }
        }
        
        [DataMember()]
        public String Zip
        {
            get
            {
                return _Zip;
            }
            set
            {
                if ((value != _Zip))
                {
                    _Zip = value;
                    OnPropertyChanged("Zip");
                }
            }
        }
        
        [DataMember()]
        public String Linkman
        {
            get
            {
                return _Linkman;
            }
            set
            {
                if ((value != _Linkman))
                {
                    _Linkman = value;
                    OnPropertyChanged("Linkman");
                }
            }
        }
        
        [DataMember()]
        public String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                if ((value != _Address))
                {
                    _Address = value;
                    OnPropertyChanged("Address");
                }
            }
        }
        
        [DataMember()]
        public String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                if ((value != _Email))
                {
                    _Email = value;
                    OnPropertyChanged("Email");
                }
            }
        }

        [DataMember()]
        public Int32 VendorType
        {
            get
            {
                return _VendorType;
            }
            set
            {
                if ((value != _VendorType))
                {
                    _VendorType = value;
                    OnPropertyChanged("VendorType");
                }
            }
        }
    }
}
