//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class VouchAuthority : Entity
    {
        
        private Guid _UserId;
        
        private Int32 _AuthorityType;
        
        [DataMember()]
        public Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if ((value != _UserId))
                {
                    _UserId = value;
                    OnPropertyChanged("UserId");
                }
            }
        }
        
        [DataMember()]
        public Int32 AuthorityType
        {
            get
            {
                return _AuthorityType;
            }
            set
            {
                if ((value != _AuthorityType))
                {
                    _AuthorityType = value;
                    OnPropertyChanged("AuthorityType");
                }
            }
        }
    }
}
