//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class VouchCodeRule : Entity
    {
        
        private String _VouchType;
        
        private String _Prefix;
        
        private String _Middle;
        
        private String _Suffix;
        
        [DataMember()]
        public String VouchType
        {
            get
            {
                return _VouchType;
            }
            set
            {
                if ((value != _VouchType))
                {
                    _VouchType = value;
                    OnPropertyChanged("VouchType");
                }
            }
        }
        
        [DataMember()]
        public String Prefix
        {
            get
            {
                return _Prefix;
            }
            set
            {
                if ((value != _Prefix))
                {
                    _Prefix = value;
                    OnPropertyChanged("Prefix");
                }
            }
        }
        
        [DataMember()]
        public String Middle
        {
            get
            {
                return _Middle;
            }
            set
            {
                if ((value != _Middle))
                {
                    _Middle = value;
                    OnPropertyChanged("Middle");
                }
            }
        }
        
        [DataMember()]
        public String Suffix
        {
            get
            {
                return _Suffix;
            }
            set
            {
                if ((value != _Suffix))
                {
                    _Suffix = value;
                    OnPropertyChanged("Suffix");
                }
            }
        }
    }
}
