//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbAssignLog : Entity
    {
        
        private Decimal _cnnAssignSerialNo;
        
        private Decimal _cnnOrderSerialNo;
        
        private String _cnvcShipDeptID;
        
        private String _cnvcShipOperID;
        
        private String _cnvcReceiveDeptID;
        
        private String _cnvcReceiveOperID;
        
        private DateTime? _cndShipDate;
        
        private DateTime? _cndReceiveDate;
        
        private String _cnvcSalesroomOperID;
        
        private String _cnvcTransportOperID;
        
        private String _cnvcStorageOperID;
        
        private String _cnvcCustomerValidate;
        
        private String _cnvcCustomerIdea;
        
        private String _cnvcOperID;
        
        private DateTime? _cndOperDate;
        
        private String _cnvcComments;
        
        private Decimal _cnnProduceSerialNo;
        
        private Int32 _cnnPrintFlag;
        
        [DataMember()]
        public Decimal cnnAssignSerialNo
        {
            get
            {
                return _cnnAssignSerialNo;
            }
            set
            {
                if ((value != _cnnAssignSerialNo))
                {
                    _cnnAssignSerialNo = value;
                    OnPropertyChanged("cnnAssignSerialNo");
                }
            }
        }
        
        [DataMember()]
        public Decimal cnnOrderSerialNo
        {
            get
            {
                return _cnnOrderSerialNo;
            }
            set
            {
                if ((value != _cnnOrderSerialNo))
                {
                    _cnnOrderSerialNo = value;
                    OnPropertyChanged("cnnOrderSerialNo");
                }
            }
        }
        
        [DataMember()]
        public String cnvcShipDeptID
        {
            get
            {
                return _cnvcShipDeptID;
            }
            set
            {
                if ((value != _cnvcShipDeptID))
                {
                    _cnvcShipDeptID = value;
                    OnPropertyChanged("cnvcShipDeptID");
                }
            }
        }
        
        [DataMember()]
        public String cnvcShipOperID
        {
            get
            {
                return _cnvcShipOperID;
            }
            set
            {
                if ((value != _cnvcShipOperID))
                {
                    _cnvcShipOperID = value;
                    OnPropertyChanged("cnvcShipOperID");
                }
            }
        }
        
        [DataMember()]
        public String cnvcReceiveDeptID
        {
            get
            {
                return _cnvcReceiveDeptID;
            }
            set
            {
                if ((value != _cnvcReceiveDeptID))
                {
                    _cnvcReceiveDeptID = value;
                    OnPropertyChanged("cnvcReceiveDeptID");
                }
            }
        }
        
        [DataMember()]
        public String cnvcReceiveOperID
        {
            get
            {
                return _cnvcReceiveOperID;
            }
            set
            {
                if ((value != _cnvcReceiveOperID))
                {
                    _cnvcReceiveOperID = value;
                    OnPropertyChanged("cnvcReceiveOperID");
                }
            }
        }
        
        [DataMember()]
        public DateTime? cndShipDate
        {
            get
            {
                return _cndShipDate;
            }
            set
            {
                if ((value != _cndShipDate))
                {
                    _cndShipDate = value;
                    OnPropertyChanged("cndShipDate");
                }
            }
        }
        
        [DataMember()]
        public DateTime? cndReceiveDate
        {
            get
            {
                return _cndReceiveDate;
            }
            set
            {
                if ((value != _cndReceiveDate))
                {
                    _cndReceiveDate = value;
                    OnPropertyChanged("cndReceiveDate");
                }
            }
        }
        
        [DataMember()]
        public String cnvcSalesroomOperID
        {
            get
            {
                return _cnvcSalesroomOperID;
            }
            set
            {
                if ((value != _cnvcSalesroomOperID))
                {
                    _cnvcSalesroomOperID = value;
                    OnPropertyChanged("cnvcSalesroomOperID");
                }
            }
        }
        
        [DataMember()]
        public String cnvcTransportOperID
        {
            get
            {
                return _cnvcTransportOperID;
            }
            set
            {
                if ((value != _cnvcTransportOperID))
                {
                    _cnvcTransportOperID = value;
                    OnPropertyChanged("cnvcTransportOperID");
                }
            }
        }
        
        [DataMember()]
        public String cnvcStorageOperID
        {
            get
            {
                return _cnvcStorageOperID;
            }
            set
            {
                if ((value != _cnvcStorageOperID))
                {
                    _cnvcStorageOperID = value;
                    OnPropertyChanged("cnvcStorageOperID");
                }
            }
        }
        
        [DataMember()]
        public String cnvcCustomerValidate
        {
            get
            {
                return _cnvcCustomerValidate;
            }
            set
            {
                if ((value != _cnvcCustomerValidate))
                {
                    _cnvcCustomerValidate = value;
                    OnPropertyChanged("cnvcCustomerValidate");
                }
            }
        }
        
        [DataMember()]
        public String cnvcCustomerIdea
        {
            get
            {
                return _cnvcCustomerIdea;
            }
            set
            {
                if ((value != _cnvcCustomerIdea))
                {
                    _cnvcCustomerIdea = value;
                    OnPropertyChanged("cnvcCustomerIdea");
                }
            }
        }
        
        [DataMember()]
        public String cnvcOperID
        {
            get
            {
                return _cnvcOperID;
            }
            set
            {
                if ((value != _cnvcOperID))
                {
                    _cnvcOperID = value;
                    OnPropertyChanged("cnvcOperID");
                }
            }
        }
        
        [DataMember()]
        public DateTime? cndOperDate
        {
            get
            {
                return _cndOperDate;
            }
            set
            {
                if ((value != _cndOperDate))
                {
                    _cndOperDate = value;
                    OnPropertyChanged("cndOperDate");
                }
            }
        }
        
        [DataMember()]
        public String cnvcComments
        {
            get
            {
                return _cnvcComments;
            }
            set
            {
                if ((value != _cnvcComments))
                {
                    _cnvcComments = value;
                    OnPropertyChanged("cnvcComments");
                }
            }
        }
        
        [DataMember()]
        public Decimal cnnProduceSerialNo
        {
            get
            {
                return _cnnProduceSerialNo;
            }
            set
            {
                if ((value != _cnnProduceSerialNo))
                {
                    _cnnProduceSerialNo = value;
                    OnPropertyChanged("cnnProduceSerialNo");
                }
            }
        }
        
        [DataMember()]
        public Int32 cnnPrintFlag
        {
            get
            {
                return _cnnPrintFlag;
            }
            set
            {
                if ((value != _cnnPrintFlag))
                {
                    _cnnPrintFlag = value;
                    OnPropertyChanged("cnnPrintFlag");
                }
            }
        }
    }
}
