//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbBillOfEnterStorageLog : Entity
    {
        
        private Decimal _cnnEnterSerialNo;
        
        private String _cnvcProviderCode;
        
        private DateTime? _cndEnterDate;
        
        private String _cnvcDeliverMan;
        
        private String _cnvcValidateOperID;
        
        private String _cnvcSafeOperID;
        
        private String _cnvcStorageOperID;
        
        private String _cnvcBillOperID;
        
        private String _cnvcEnterType;
        
        [DataMember()]
        public Decimal cnnEnterSerialNo
        {
            get
            {
                return _cnnEnterSerialNo;
            }
            set
            {
                if ((value != _cnnEnterSerialNo))
                {
                    _cnnEnterSerialNo = value;
                    OnPropertyChanged("cnnEnterSerialNo");
                }
            }
        }
        
        [DataMember()]
        public String cnvcProviderCode
        {
            get
            {
                return _cnvcProviderCode;
            }
            set
            {
                if ((value != _cnvcProviderCode))
                {
                    _cnvcProviderCode = value;
                    OnPropertyChanged("cnvcProviderCode");
                }
            }
        }
        
        [DataMember()]
        public DateTime? cndEnterDate
        {
            get
            {
                return _cndEnterDate;
            }
            set
            {
                if ((value != _cndEnterDate))
                {
                    _cndEnterDate = value;
                    OnPropertyChanged("cndEnterDate");
                }
            }
        }
        
        [DataMember()]
        public String cnvcDeliverMan
        {
            get
            {
                return _cnvcDeliverMan;
            }
            set
            {
                if ((value != _cnvcDeliverMan))
                {
                    _cnvcDeliverMan = value;
                    OnPropertyChanged("cnvcDeliverMan");
                }
            }
        }
        
        [DataMember()]
        public String cnvcValidateOperID
        {
            get
            {
                return _cnvcValidateOperID;
            }
            set
            {
                if ((value != _cnvcValidateOperID))
                {
                    _cnvcValidateOperID = value;
                    OnPropertyChanged("cnvcValidateOperID");
                }
            }
        }
        
        [DataMember()]
        public String cnvcSafeOperID
        {
            get
            {
                return _cnvcSafeOperID;
            }
            set
            {
                if ((value != _cnvcSafeOperID))
                {
                    _cnvcSafeOperID = value;
                    OnPropertyChanged("cnvcSafeOperID");
                }
            }
        }
        
        [DataMember()]
        public String cnvcStorageOperID
        {
            get
            {
                return _cnvcStorageOperID;
            }
            set
            {
                if ((value != _cnvcStorageOperID))
                {
                    _cnvcStorageOperID = value;
                    OnPropertyChanged("cnvcStorageOperID");
                }
            }
        }
        
        [DataMember()]
        public String cnvcBillOperID
        {
            get
            {
                return _cnvcBillOperID;
            }
            set
            {
                if ((value != _cnvcBillOperID))
                {
                    _cnvcBillOperID = value;
                    OnPropertyChanged("cnvcBillOperID");
                }
            }
        }
        
        [DataMember()]
        public String cnvcEnterType
        {
            get
            {
                return _cnvcEnterType;
            }
            set
            {
                if ((value != _cnvcEnterType))
                {
                    _cnvcEnterType = value;
                    OnPropertyChanged("cnvcEnterType");
                }
            }
        }
    }
}
