//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbBusiIncomeReport : Entity
    {
        
        private String _vcDateZoom;
        
        private String _vcDeptID;
        
        private String _Type;
        
        private Int32 _REP1;
        
        private Int32 _REP2;
        
        private Decimal _REP3;
        
        private Decimal _REP4;
        
        private Decimal _REP5;
        
        private Decimal _REP6;
        
        private Int32 _REP7;
        
        private Int32? _ReNo;
        
        private DateTime? _dtCreateDate;
        
        [DataMember()]
        public String vcDateZoom
        {
            get
            {
                return _vcDateZoom;
            }
            set
            {
                if ((value != _vcDateZoom))
                {
                    _vcDateZoom = value;
                    OnPropertyChanged("vcDateZoom");
                }
            }
        }
        
        [DataMember()]
        public String vcDeptID
        {
            get
            {
                return _vcDeptID;
            }
            set
            {
                if ((value != _vcDeptID))
                {
                    _vcDeptID = value;
                    OnPropertyChanged("vcDeptID");
                }
            }
        }
        
        [DataMember()]
        public String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                if ((value != _Type))
                {
                    _Type = value;
                    OnPropertyChanged("Type");
                }
            }
        }
        
        [DataMember()]
        public Int32 REP1
        {
            get
            {
                return _REP1;
            }
            set
            {
                if ((value != _REP1))
                {
                    _REP1 = value;
                    OnPropertyChanged("REP1");
                }
            }
        }
        
        [DataMember()]
        public Int32 REP2
        {
            get
            {
                return _REP2;
            }
            set
            {
                if ((value != _REP2))
                {
                    _REP2 = value;
                    OnPropertyChanged("REP2");
                }
            }
        }
        
        [DataMember()]
        public Decimal REP3
        {
            get
            {
                return _REP3;
            }
            set
            {
                if ((value != _REP3))
                {
                    _REP3 = value;
                    OnPropertyChanged("REP3");
                }
            }
        }
        
        [DataMember()]
        public Decimal REP4
        {
            get
            {
                return _REP4;
            }
            set
            {
                if ((value != _REP4))
                {
                    _REP4 = value;
                    OnPropertyChanged("REP4");
                }
            }
        }
        
        [DataMember()]
        public Decimal REP5
        {
            get
            {
                return _REP5;
            }
            set
            {
                if ((value != _REP5))
                {
                    _REP5 = value;
                    OnPropertyChanged("REP5");
                }
            }
        }
        
        [DataMember()]
        public Decimal REP6
        {
            get
            {
                return _REP6;
            }
            set
            {
                if ((value != _REP6))
                {
                    _REP6 = value;
                    OnPropertyChanged("REP6");
                }
            }
        }
        
        [DataMember()]
        public Int32 REP7
        {
            get
            {
                return _REP7;
            }
            set
            {
                if ((value != _REP7))
                {
                    _REP7 = value;
                    OnPropertyChanged("REP7");
                }
            }
        }
        
        [DataMember()]
        public Int32? ReNo
        {
            get
            {
                return _ReNo;
            }
            set
            {
                if ((value != _ReNo))
                {
                    _ReNo = value;
                    OnPropertyChanged("ReNo");
                }
            }
        }
        
        [DataMember()]
        public DateTime? dtCreateDate
        {
            get
            {
                return _dtCreateDate;
            }
            set
            {
                if ((value != _dtCreateDate))
                {
                    _dtCreateDate = value;
                    OnPropertyChanged("dtCreateDate");
                }
            }
        }
    }
}
