//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbComputationUnit : Entity
    {
        
        private String _cnvcComunitCode;
        
        private String _cnvcComUnitName;
        
        private String _cnvcGroupCode;
        
        private Boolean _cnbMainUnit;
        
        private Decimal _cniChangRate;
        
        [DataMember()]
        public String cnvcComunitCode
        {
            get
            {
                return _cnvcComunitCode;
            }
            set
            {
                if ((value != _cnvcComunitCode))
                {
                    _cnvcComunitCode = value;
                    OnPropertyChanged("cnvcComunitCode");
                }
            }
        }
        
        [DataMember()]
        public String cnvcComUnitName
        {
            get
            {
                return _cnvcComUnitName;
            }
            set
            {
                if ((value != _cnvcComUnitName))
                {
                    _cnvcComUnitName = value;
                    OnPropertyChanged("cnvcComUnitName");
                }
            }
        }
        
        [DataMember()]
        public String cnvcGroupCode
        {
            get
            {
                return _cnvcGroupCode;
            }
            set
            {
                if ((value != _cnvcGroupCode))
                {
                    _cnvcGroupCode = value;
                    OnPropertyChanged("cnvcGroupCode");
                }
            }
        }
        
        [DataMember()]
        public Boolean cnbMainUnit
        {
            get
            {
                return _cnbMainUnit;
            }
            set
            {
                if ((value != _cnbMainUnit))
                {
                    _cnbMainUnit = value;
                    OnPropertyChanged("cnbMainUnit");
                }
            }
        }
        
        [DataMember()]
        public Decimal cniChangRate
        {
            get
            {
                return _cniChangRate;
            }
            set
            {
                if ((value != _cniChangRate))
                {
                    _cniChangRate = value;
                    OnPropertyChanged("cniChangRate");
                }
            }
        }
    }
}
