//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbConsItemOther : Entity
    {
        
        private Int64 _iSerial;
        
        private String _vcGoodsID;
        
        private Int64? _iAssID;
        
        private String _vcCardID;
        
        private Decimal? _nPrice;
        
        private Int32? _iCount;
        
        private Decimal? _nTRate;
        
        private Decimal? _nFee;
        
        private String _vcComments;
        
        private String _cFlag;
        
        private DateTime? _dtConsDate;
        
        private String _vcOperName;
        
        private String _vcDeptID;
        
        [DataMember()]
        public Int64 iSerial
        {
            get
            {
                return _iSerial;
            }
            set
            {
                if ((value != _iSerial))
                {
                    _iSerial = value;
                    OnPropertyChanged("iSerial");
                }
            }
        }
        
        [DataMember()]
        public String vcGoodsID
        {
            get
            {
                return _vcGoodsID;
            }
            set
            {
                if ((value != _vcGoodsID))
                {
                    _vcGoodsID = value;
                    OnPropertyChanged("vcGoodsID");
                }
            }
        }
        
        [DataMember()]
        public Int64? iAssID
        {
            get
            {
                return _iAssID;
            }
            set
            {
                if ((value != _iAssID))
                {
                    _iAssID = value;
                    OnPropertyChanged("iAssID");
                }
            }
        }
        
        [DataMember()]
        public String vcCardID
        {
            get
            {
                return _vcCardID;
            }
            set
            {
                if ((value != _vcCardID))
                {
                    _vcCardID = value;
                    OnPropertyChanged("vcCardID");
                }
            }
        }
        
        [DataMember()]
        public Decimal? nPrice
        {
            get
            {
                return _nPrice;
            }
            set
            {
                if ((value != _nPrice))
                {
                    _nPrice = value;
                    OnPropertyChanged("nPrice");
                }
            }
        }
        
        [DataMember()]
        public Int32? iCount
        {
            get
            {
                return _iCount;
            }
            set
            {
                if ((value != _iCount))
                {
                    _iCount = value;
                    OnPropertyChanged("iCount");
                }
            }
        }
        
        [DataMember()]
        public Decimal? nTRate
        {
            get
            {
                return _nTRate;
            }
            set
            {
                if ((value != _nTRate))
                {
                    _nTRate = value;
                    OnPropertyChanged("nTRate");
                }
            }
        }
        
        [DataMember()]
        public Decimal? nFee
        {
            get
            {
                return _nFee;
            }
            set
            {
                if ((value != _nFee))
                {
                    _nFee = value;
                    OnPropertyChanged("nFee");
                }
            }
        }
        
        [DataMember()]
        public String vcComments
        {
            get
            {
                return _vcComments;
            }
            set
            {
                if ((value != _vcComments))
                {
                    _vcComments = value;
                    OnPropertyChanged("vcComments");
                }
            }
        }
        
        [DataMember()]
        public String cFlag
        {
            get
            {
                return _cFlag;
            }
            set
            {
                if ((value != _cFlag))
                {
                    _cFlag = value;
                    OnPropertyChanged("cFlag");
                }
            }
        }
        
        [DataMember()]
        public DateTime? dtConsDate
        {
            get
            {
                return _dtConsDate;
            }
            set
            {
                if ((value != _dtConsDate))
                {
                    _dtConsDate = value;
                    OnPropertyChanged("dtConsDate");
                }
            }
        }
        
        [DataMember()]
        public String vcOperName
        {
            get
            {
                return _vcOperName;
            }
            set
            {
                if ((value != _vcOperName))
                {
                    _vcOperName = value;
                    OnPropertyChanged("vcOperName");
                }
            }
        }
        
        [DataMember()]
        public String vcDeptID
        {
            get
            {
                return _vcDeptID;
            }
            set
            {
                if ((value != _vcDeptID))
                {
                    _vcDeptID = value;
                    OnPropertyChanged("vcDeptID");
                }
            }
        }
    }
}
