//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbDataSoftUpdateLog : Entity
    {
        
        private String _vcFileName;
        
        private Int64? _FileSize;
        
        private Int32? _FileCount;
        
        private DateTime? _dtStartDate;
        
        private DateTime? _dtFinDate;
        
        private String _Type;
        
        [DataMember()]
        public String vcFileName
        {
            get
            {
                return _vcFileName;
            }
            set
            {
                if ((value != _vcFileName))
                {
                    _vcFileName = value;
                    OnPropertyChanged("vcFileName");
                }
            }
        }
        
        [DataMember()]
        public Int64? FileSize
        {
            get
            {
                return _FileSize;
            }
            set
            {
                if ((value != _FileSize))
                {
                    _FileSize = value;
                    OnPropertyChanged("FileSize");
                }
            }
        }
        
        [DataMember()]
        public Int32? FileCount
        {
            get
            {
                return _FileCount;
            }
            set
            {
                if ((value != _FileCount))
                {
                    _FileCount = value;
                    OnPropertyChanged("FileCount");
                }
            }
        }
        
        [DataMember()]
        public DateTime? dtStartDate
        {
            get
            {
                return _dtStartDate;
            }
            set
            {
                if ((value != _dtStartDate))
                {
                    _dtStartDate = value;
                    OnPropertyChanged("dtStartDate");
                }
            }
        }
        
        [DataMember()]
        public DateTime? dtFinDate
        {
            get
            {
                return _dtFinDate;
            }
            set
            {
                if ((value != _dtFinDate))
                {
                    _dtFinDate = value;
                    OnPropertyChanged("dtFinDate");
                }
            }
        }
        
        [DataMember()]
        public String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                if ((value != _Type))
                {
                    _Type = value;
                    OnPropertyChanged("Type");
                }
            }
        }
    }
}
