//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbDept : Entity
    {
        
        private String _cnvcDeptName;
        
        private String _cnvcDeptID;
        
        private String _cnvcDeptType;
        
        private String _cnvcParentDeptID;
        
        private String _cnvcComments;
        
        private Int32? _cnnPriority;
        
        [DataMember()]
        public String cnvcDeptName
        {
            get
            {
                return _cnvcDeptName;
            }
            set
            {
                if ((value != _cnvcDeptName))
                {
                    _cnvcDeptName = value;
                    OnPropertyChanged("cnvcDeptName");
                }
            }
        }
        
        [DataMember()]
        public String cnvcDeptID
        {
            get
            {
                return _cnvcDeptID;
            }
            set
            {
                if ((value != _cnvcDeptID))
                {
                    _cnvcDeptID = value;
                    OnPropertyChanged("cnvcDeptID");
                }
            }
        }
        
        [DataMember()]
        public String cnvcDeptType
        {
            get
            {
                return _cnvcDeptType;
            }
            set
            {
                if ((value != _cnvcDeptType))
                {
                    _cnvcDeptType = value;
                    OnPropertyChanged("cnvcDeptType");
                }
            }
        }
        
        [DataMember()]
        public String cnvcParentDeptID
        {
            get
            {
                return _cnvcParentDeptID;
            }
            set
            {
                if ((value != _cnvcParentDeptID))
                {
                    _cnvcParentDeptID = value;
                    OnPropertyChanged("cnvcParentDeptID");
                }
            }
        }
        
        [DataMember()]
        public String cnvcComments
        {
            get
            {
                return _cnvcComments;
            }
            set
            {
                if ((value != _cnvcComments))
                {
                    _cnvcComments = value;
                    OnPropertyChanged("cnvcComments");
                }
            }
        }
        
        [DataMember()]
        public Int32? cnnPriority
        {
            get
            {
                return _cnnPriority;
            }
            set
            {
                if ((value != _cnnPriority))
                {
                    _cnnPriority = value;
                    OnPropertyChanged("cnnPriority");
                }
            }
        }
    }
}
