//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbFunc : Entity
    {
        
        private String _cnvcFuncName;
        
        private String _cnvcFuncParentName;
        
        private String _cnvcFuncAddress;
        
        private String _cnvcFuncType;
        
        [DataMember()]
        public String cnvcFuncName
        {
            get
            {
                return _cnvcFuncName;
            }
            set
            {
                if ((value != _cnvcFuncName))
                {
                    _cnvcFuncName = value;
                    OnPropertyChanged("cnvcFuncName");
                }
            }
        }
        
        [DataMember()]
        public String cnvcFuncParentName
        {
            get
            {
                return _cnvcFuncParentName;
            }
            set
            {
                if ((value != _cnvcFuncParentName))
                {
                    _cnvcFuncParentName = value;
                    OnPropertyChanged("cnvcFuncParentName");
                }
            }
        }
        
        [DataMember()]
        public String cnvcFuncAddress
        {
            get
            {
                return _cnvcFuncAddress;
            }
            set
            {
                if ((value != _cnvcFuncAddress))
                {
                    _cnvcFuncAddress = value;
                    OnPropertyChanged("cnvcFuncAddress");
                }
            }
        }
        
        [DataMember()]
        public String cnvcFuncType
        {
            get
            {
                return _cnvcFuncType;
            }
            set
            {
                if ((value != _cnvcFuncType))
                {
                    _cnvcFuncType = value;
                    OnPropertyChanged("cnvcFuncType");
                }
            }
        }
    }
}
