//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbGoods : Entity
    {
        
        private String _vcGoodsID;
        
        private String _vcGoodsName;
        
        private String _vcSpell;
        
        private Decimal? _nPrice;
        
        private Decimal? _nRate;
        
        private Int32? _iIgValue;
        
        private String _cNewFlag;
        
        private String _vcComments;
        
        private String _vcGoodsType;
        
        [DataMember()]
        public String vcGoodsID
        {
            get
            {
                return _vcGoodsID;
            }
            set
            {
                if ((value != _vcGoodsID))
                {
                    _vcGoodsID = value;
                    OnPropertyChanged("vcGoodsID");
                }
            }
        }
        
        [DataMember()]
        public String vcGoodsName
        {
            get
            {
                return _vcGoodsName;
            }
            set
            {
                if ((value != _vcGoodsName))
                {
                    _vcGoodsName = value;
                    OnPropertyChanged("vcGoodsName");
                }
            }
        }
        
        [DataMember()]
        public String vcSpell
        {
            get
            {
                return _vcSpell;
            }
            set
            {
                if ((value != _vcSpell))
                {
                    _vcSpell = value;
                    OnPropertyChanged("vcSpell");
                }
            }
        }
        
        [DataMember()]
        public Decimal? nPrice
        {
            get
            {
                return _nPrice;
            }
            set
            {
                if ((value != _nPrice))
                {
                    _nPrice = value;
                    OnPropertyChanged("nPrice");
                }
            }
        }
        
        [DataMember()]
        public Decimal? nRate
        {
            get
            {
                return _nRate;
            }
            set
            {
                if ((value != _nRate))
                {
                    _nRate = value;
                    OnPropertyChanged("nRate");
                }
            }
        }
        
        [DataMember()]
        public Int32? iIgValue
        {
            get
            {
                return _iIgValue;
            }
            set
            {
                if ((value != _iIgValue))
                {
                    _iIgValue = value;
                    OnPropertyChanged("iIgValue");
                }
            }
        }
        
        [DataMember()]
        public String cNewFlag
        {
            get
            {
                return _cNewFlag;
            }
            set
            {
                if ((value != _cNewFlag))
                {
                    _cNewFlag = value;
                    OnPropertyChanged("cNewFlag");
                }
            }
        }
        
        [DataMember()]
        public String vcComments
        {
            get
            {
                return _vcComments;
            }
            set
            {
                if ((value != _vcComments))
                {
                    _vcComments = value;
                    OnPropertyChanged("vcComments");
                }
            }
        }
        
        [DataMember()]
        public String vcGoodsType
        {
            get
            {
                return _vcGoodsType;
            }
            set
            {
                if ((value != _vcGoodsType))
                {
                    _vcGoodsType = value;
                    OnPropertyChanged("vcGoodsType");
                }
            }
        }
    }
}
