//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbMacAddress : Entity
    {
        
        private String _vcMacAddress;
        
        private String _vcName;
        
        [DataMember()]
        public String vcMacAddress
        {
            get
            {
                return _vcMacAddress;
            }
            set
            {
                if ((value != _vcMacAddress))
                {
                    _vcMacAddress = value;
                    OnPropertyChanged("vcMacAddress");
                }
            }
        }
        
        [DataMember()]
        public String vcName
        {
            get
            {
                return _vcName;
            }
            set
            {
                if ((value != _vcName))
                {
                    _vcName = value;
                    OnPropertyChanged("vcName");
                }
            }
        }
    }
}
