//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbMakeLog : Entity
    {
        
        private Decimal _cnnProduceSerialNo;
        
        private Decimal _cnnMakeSerialNo;
        
        private String _cnvcGroup;
        
        private String _cnvcMakeName;
        
        private String _cnvcMakeType;
        
        private String _cnvcClass;
        
        private String _cnvcInChargeOperID;
        
        private String _cnvcOperID;
        
        private DateTime? _cndOperDate;
        
        [DataMember()]
        public Decimal cnnProduceSerialNo
        {
            get
            {
                return _cnnProduceSerialNo;
            }
            set
            {
                if ((value != _cnnProduceSerialNo))
                {
                    _cnnProduceSerialNo = value;
                    OnPropertyChanged("cnnProduceSerialNo");
                }
            }
        }
        
        [DataMember()]
        public Decimal cnnMakeSerialNo
        {
            get
            {
                return _cnnMakeSerialNo;
            }
            set
            {
                if ((value != _cnnMakeSerialNo))
                {
                    _cnnMakeSerialNo = value;
                    OnPropertyChanged("cnnMakeSerialNo");
                }
            }
        }
        
        [DataMember()]
        public String cnvcGroup
        {
            get
            {
                return _cnvcGroup;
            }
            set
            {
                if ((value != _cnvcGroup))
                {
                    _cnvcGroup = value;
                    OnPropertyChanged("cnvcGroup");
                }
            }
        }
        
        [DataMember()]
        public String cnvcMakeName
        {
            get
            {
                return _cnvcMakeName;
            }
            set
            {
                if ((value != _cnvcMakeName))
                {
                    _cnvcMakeName = value;
                    OnPropertyChanged("cnvcMakeName");
                }
            }
        }
        
        [DataMember()]
        public String cnvcMakeType
        {
            get
            {
                return _cnvcMakeType;
            }
            set
            {
                if ((value != _cnvcMakeType))
                {
                    _cnvcMakeType = value;
                    OnPropertyChanged("cnvcMakeType");
                }
            }
        }
        
        [DataMember()]
        public String cnvcClass
        {
            get
            {
                return _cnvcClass;
            }
            set
            {
                if ((value != _cnvcClass))
                {
                    _cnvcClass = value;
                    OnPropertyChanged("cnvcClass");
                }
            }
        }
        
        [DataMember()]
        public String cnvcInChargeOperID
        {
            get
            {
                return _cnvcInChargeOperID;
            }
            set
            {
                if ((value != _cnvcInChargeOperID))
                {
                    _cnvcInChargeOperID = value;
                    OnPropertyChanged("cnvcInChargeOperID");
                }
            }
        }
        
        [DataMember()]
        public String cnvcOperID
        {
            get
            {
                return _cnvcOperID;
            }
            set
            {
                if ((value != _cnvcOperID))
                {
                    _cnvcOperID = value;
                    OnPropertyChanged("cnvcOperID");
                }
            }
        }
        
        [DataMember()]
        public DateTime? cndOperDate
        {
            get
            {
                return _cndOperDate;
            }
            set
            {
                if ((value != _cndOperDate))
                {
                    _cndOperDate = value;
                    OnPropertyChanged("cndOperDate");
                }
            }
        }
    }
}
