//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbMoveDetail : Entity
    {
        
        private Int64 _cnnMoveSerialNo;
        
        private String _cnvcProductCode;
        
        private String _cnvcProductName;
        
        private String _cnvcUnit;
        
        private Decimal? _cnnMoveCount;
        
        private Decimal? _cnnRealMoveCount;
        
        private String _cnvcComments;
        
        [DataMember()]
        public Int64 cnnMoveSerialNo
        {
            get
            {
                return _cnnMoveSerialNo;
            }
            set
            {
                if ((value != _cnnMoveSerialNo))
                {
                    _cnnMoveSerialNo = value;
                    OnPropertyChanged("cnnMoveSerialNo");
                }
            }
        }
        
        [DataMember()]
        public String cnvcProductCode
        {
            get
            {
                return _cnvcProductCode;
            }
            set
            {
                if ((value != _cnvcProductCode))
                {
                    _cnvcProductCode = value;
                    OnPropertyChanged("cnvcProductCode");
                }
            }
        }
        
        [DataMember()]
        public String cnvcProductName
        {
            get
            {
                return _cnvcProductName;
            }
            set
            {
                if ((value != _cnvcProductName))
                {
                    _cnvcProductName = value;
                    OnPropertyChanged("cnvcProductName");
                }
            }
        }
        
        [DataMember()]
        public String cnvcUnit
        {
            get
            {
                return _cnvcUnit;
            }
            set
            {
                if ((value != _cnvcUnit))
                {
                    _cnvcUnit = value;
                    OnPropertyChanged("cnvcUnit");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnMoveCount
        {
            get
            {
                return _cnnMoveCount;
            }
            set
            {
                if ((value != _cnnMoveCount))
                {
                    _cnnMoveCount = value;
                    OnPropertyChanged("cnnMoveCount");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnRealMoveCount
        {
            get
            {
                return _cnnRealMoveCount;
            }
            set
            {
                if ((value != _cnnRealMoveCount))
                {
                    _cnnRealMoveCount = value;
                    OnPropertyChanged("cnnRealMoveCount");
                }
            }
        }
        
        [DataMember()]
        public String cnvcComments
        {
            get
            {
                return _cnvcComments;
            }
            set
            {
                if ((value != _cnvcComments))
                {
                    _cnvcComments = value;
                    OnPropertyChanged("cnvcComments");
                }
            }
        }
    }
}
