//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbOperLog : Entity
    {
        
        private Int64 _cnnOperSerialNo;
        
        private String _cnvcOperType;
        
        private String _cnvcOperID;
        
        private String _cnvcDeptID;
        
        private DateTime? _cndOperDate;
        
        private String _cnvcComments;
        
        [DataMember()]
        public Int64 cnnOperSerialNo
        {
            get
            {
                return _cnnOperSerialNo;
            }
            set
            {
                if ((value != _cnnOperSerialNo))
                {
                    _cnnOperSerialNo = value;
                    OnPropertyChanged("cnnOperSerialNo");
                }
            }
        }
        
        [DataMember()]
        public String cnvcOperType
        {
            get
            {
                return _cnvcOperType;
            }
            set
            {
                if ((value != _cnvcOperType))
                {
                    _cnvcOperType = value;
                    OnPropertyChanged("cnvcOperType");
                }
            }
        }
        
        [DataMember()]
        public String cnvcOperID
        {
            get
            {
                return _cnvcOperID;
            }
            set
            {
                if ((value != _cnvcOperID))
                {
                    _cnvcOperID = value;
                    OnPropertyChanged("cnvcOperID");
                }
            }
        }
        
        [DataMember()]
        public String cnvcDeptID
        {
            get
            {
                return _cnvcDeptID;
            }
            set
            {
                if ((value != _cnvcDeptID))
                {
                    _cnvcDeptID = value;
                    OnPropertyChanged("cnvcDeptID");
                }
            }
        }
        
        [DataMember()]
        public DateTime? cndOperDate
        {
            get
            {
                return _cndOperDate;
            }
            set
            {
                if ((value != _cndOperDate))
                {
                    _cndOperDate = value;
                    OnPropertyChanged("cndOperDate");
                }
            }
        }
        
        [DataMember()]
        public String cnvcComments
        {
            get
            {
                return _cnvcComments;
            }
            set
            {
                if ((value != _cnvcComments))
                {
                    _cnvcComments = value;
                    OnPropertyChanged("cnvcComments");
                }
            }
        }
    }
}
