//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbOperStandard : Entity
    {
        
        private String _cnvcProductCode;
        
        private Int32 _cnnSort;
        
        private String _cnvcStandard;
        
        private String _cnvcKey;
        
        [DataMember()]
        public String cnvcProductCode
        {
            get
            {
                return _cnvcProductCode;
            }
            set
            {
                if ((value != _cnvcProductCode))
                {
                    _cnvcProductCode = value;
                    OnPropertyChanged("cnvcProductCode");
                }
            }
        }
        
        [DataMember()]
        public Int32 cnnSort
        {
            get
            {
                return _cnnSort;
            }
            set
            {
                if ((value != _cnnSort))
                {
                    _cnnSort = value;
                    OnPropertyChanged("cnnSort");
                }
            }
        }
        
        [DataMember()]
        public String cnvcStandard
        {
            get
            {
                return _cnvcStandard;
            }
            set
            {
                if ((value != _cnvcStandard))
                {
                    _cnvcStandard = value;
                    OnPropertyChanged("cnvcStandard");
                }
            }
        }
        
        [DataMember()]
        public String cnvcKey
        {
            get
            {
                return _cnvcKey;
            }
            set
            {
                if ((value != _cnvcKey))
                {
                    _cnvcKey = value;
                    OnPropertyChanged("cnvcKey");
                }
            }
        }
    }
}
