//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbOperFunc : Entity
    {
        
        private String _vcOperID;
        
        private String _vcFuncName;
        
        private String _vcFuncAddress;
        
        [DataMember()]
        public String vcOperID
        {
            get
            {
                return _vcOperID;
            }
            set
            {
                if ((value != _vcOperID))
                {
                    _vcOperID = value;
                    OnPropertyChanged("vcOperID");
                }
            }
        }
        
        [DataMember()]
        public String vcFuncName
        {
            get
            {
                return _vcFuncName;
            }
            set
            {
                if ((value != _vcFuncName))
                {
                    _vcFuncName = value;
                    OnPropertyChanged("vcFuncName");
                }
            }
        }
        
        [DataMember()]
        public String vcFuncAddress
        {
            get
            {
                return _vcFuncAddress;
            }
            set
            {
                if ((value != _vcFuncAddress))
                {
                    _vcFuncAddress = value;
                    OnPropertyChanged("vcFuncAddress");
                }
            }
        }
    }
}
