//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbOrderSerialNo : Entity
    {
        
        private Int64 _cnnSerialNo;
        
        private String _cnvcFill;
        
        [DataMember()]
        public Int64 cnnSerialNo
        {
            get
            {
                return _cnnSerialNo;
            }
            set
            {
                if ((value != _cnnSerialNo))
                {
                    _cnnSerialNo = value;
                    OnPropertyChanged("cnnSerialNo");
                }
            }
        }
        
        [DataMember()]
        public String cnvcFill
        {
            get
            {
                return _cnvcFill;
            }
            set
            {
                if ((value != _cnvcFill))
                {
                    _cnvcFill = value;
                    OnPropertyChanged("cnvcFill");
                }
            }
        }
    }
}
