//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbOrderAddLog : Entity
    {
        
        private Decimal _cnnAddSerialNo;
        
        private Decimal _cnnOrderSerialNo;
        
        private String _cnvcProductCode;
        
        private String _cnvcProductName;
        
        private Decimal? _cnnAddCount;
        
        private String _cnvcUnit;
        
        private Decimal? _cnnPrice;
        
        private Decimal? _cnnSum;
        
        private String _cnvcAddType;
        
        private String _cnvcAddState;
        
        private String _cnvcAddComments;
        
        private String _cnvcOperID;
        
        private DateTime? _cndOperDate;
        
        [DataMember()]
        public Decimal cnnAddSerialNo
        {
            get
            {
                return _cnnAddSerialNo;
            }
            set
            {
                if ((value != _cnnAddSerialNo))
                {
                    _cnnAddSerialNo = value;
                    OnPropertyChanged("cnnAddSerialNo");
                }
            }
        }
        
        [DataMember()]
        public Decimal cnnOrderSerialNo
        {
            get
            {
                return _cnnOrderSerialNo;
            }
            set
            {
                if ((value != _cnnOrderSerialNo))
                {
                    _cnnOrderSerialNo = value;
                    OnPropertyChanged("cnnOrderSerialNo");
                }
            }
        }
        
        [DataMember()]
        public String cnvcProductCode
        {
            get
            {
                return _cnvcProductCode;
            }
            set
            {
                if ((value != _cnvcProductCode))
                {
                    _cnvcProductCode = value;
                    OnPropertyChanged("cnvcProductCode");
                }
            }
        }
        
        [DataMember()]
        public String cnvcProductName
        {
            get
            {
                return _cnvcProductName;
            }
            set
            {
                if ((value != _cnvcProductName))
                {
                    _cnvcProductName = value;
                    OnPropertyChanged("cnvcProductName");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnAddCount
        {
            get
            {
                return _cnnAddCount;
            }
            set
            {
                if ((value != _cnnAddCount))
                {
                    _cnnAddCount = value;
                    OnPropertyChanged("cnnAddCount");
                }
            }
        }
        
        [DataMember()]
        public String cnvcUnit
        {
            get
            {
                return _cnvcUnit;
            }
            set
            {
                if ((value != _cnvcUnit))
                {
                    _cnvcUnit = value;
                    OnPropertyChanged("cnvcUnit");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnPrice
        {
            get
            {
                return _cnnPrice;
            }
            set
            {
                if ((value != _cnnPrice))
                {
                    _cnnPrice = value;
                    OnPropertyChanged("cnnPrice");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnSum
        {
            get
            {
                return _cnnSum;
            }
            set
            {
                if ((value != _cnnSum))
                {
                    _cnnSum = value;
                    OnPropertyChanged("cnnSum");
                }
            }
        }
        
        [DataMember()]
        public String cnvcAddType
        {
            get
            {
                return _cnvcAddType;
            }
            set
            {
                if ((value != _cnvcAddType))
                {
                    _cnvcAddType = value;
                    OnPropertyChanged("cnvcAddType");
                }
            }
        }
        
        [DataMember()]
        public String cnvcAddState
        {
            get
            {
                return _cnvcAddState;
            }
            set
            {
                if ((value != _cnvcAddState))
                {
                    _cnvcAddState = value;
                    OnPropertyChanged("cnvcAddState");
                }
            }
        }
        
        [DataMember()]
        public String cnvcAddComments
        {
            get
            {
                return _cnvcAddComments;
            }
            set
            {
                if ((value != _cnvcAddComments))
                {
                    _cnvcAddComments = value;
                    OnPropertyChanged("cnvcAddComments");
                }
            }
        }
        
        [DataMember()]
        public String cnvcOperID
        {
            get
            {
                return _cnvcOperID;
            }
            set
            {
                if ((value != _cnvcOperID))
                {
                    _cnvcOperID = value;
                    OnPropertyChanged("cnvcOperID");
                }
            }
        }
        
        [DataMember()]
        public DateTime? cndOperDate
        {
            get
            {
                return _cndOperDate;
            }
            set
            {
                if ((value != _cndOperDate))
                {
                    _cndOperDate = value;
                    OnPropertyChanged("cndOperDate");
                }
            }
        }
    }
}
