//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbProductClass : Entity
    {
        
        private String _cnvcProductType;
        
        private String _cnvcProductClassName;
        
        private String _cnvcProductClassCode;
        
        private String _cnvcComments;
        
        private Int32 _cnnDays;
        
        [DataMember()]
        public String cnvcProductType
        {
            get
            {
                return _cnvcProductType;
            }
            set
            {
                if ((value != _cnvcProductType))
                {
                    _cnvcProductType = value;
                    OnPropertyChanged("cnvcProductType");
                }
            }
        }
        
        [DataMember()]
        public String cnvcProductClassName
        {
            get
            {
                return _cnvcProductClassName;
            }
            set
            {
                if ((value != _cnvcProductClassName))
                {
                    _cnvcProductClassName = value;
                    OnPropertyChanged("cnvcProductClassName");
                }
            }
        }
        
        [DataMember()]
        public String cnvcProductClassCode
        {
            get
            {
                return _cnvcProductClassCode;
            }
            set
            {
                if ((value != _cnvcProductClassCode))
                {
                    _cnvcProductClassCode = value;
                    OnPropertyChanged("cnvcProductClassCode");
                }
            }
        }
        
        [DataMember()]
        public String cnvcComments
        {
            get
            {
                return _cnvcComments;
            }
            set
            {
                if ((value != _cnvcComments))
                {
                    _cnvcComments = value;
                    OnPropertyChanged("cnvcComments");
                }
            }
        }
        
        [DataMember()]
        public Int32 cnnDays
        {
            get
            {
                return _cnnDays;
            }
            set
            {
                if ((value != _cnnDays))
                {
                    _cnnDays = value;
                    OnPropertyChanged("cnnDays");
                }
            }
        }
    }
}
