//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbProduceDetailAdd : Entity
    {
        
        private Decimal _cnnProduceSerialNo;
        
        private Decimal _cnnAddSerialNo;
        
        private String _cnvcCode;
        
        private String _cnvcName;
        
        private String _cnvcUnit;
        
        private Decimal? _cnnCount;
        
        private String _cnvcState;
        
        [DataMember()]
        public Decimal cnnProduceSerialNo
        {
            get
            {
                return _cnnProduceSerialNo;
            }
            set
            {
                if ((value != _cnnProduceSerialNo))
                {
                    _cnnProduceSerialNo = value;
                    OnPropertyChanged("cnnProduceSerialNo");
                }
            }
        }
        
        [DataMember()]
        public Decimal cnnAddSerialNo
        {
            get
            {
                return _cnnAddSerialNo;
            }
            set
            {
                if ((value != _cnnAddSerialNo))
                {
                    _cnnAddSerialNo = value;
                    OnPropertyChanged("cnnAddSerialNo");
                }
            }
        }
        
        [DataMember()]
        public String cnvcCode
        {
            get
            {
                return _cnvcCode;
            }
            set
            {
                if ((value != _cnvcCode))
                {
                    _cnvcCode = value;
                    OnPropertyChanged("cnvcCode");
                }
            }
        }
        
        [DataMember()]
        public String cnvcName
        {
            get
            {
                return _cnvcName;
            }
            set
            {
                if ((value != _cnvcName))
                {
                    _cnvcName = value;
                    OnPropertyChanged("cnvcName");
                }
            }
        }
        
        [DataMember()]
        public String cnvcUnit
        {
            get
            {
                return _cnvcUnit;
            }
            set
            {
                if ((value != _cnvcUnit))
                {
                    _cnvcUnit = value;
                    OnPropertyChanged("cnvcUnit");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnCount
        {
            get
            {
                return _cnnCount;
            }
            set
            {
                if ((value != _cnnCount))
                {
                    _cnnCount = value;
                    OnPropertyChanged("cnnCount");
                }
            }
        }
        
        [DataMember()]
        public String cnvcState
        {
            get
            {
                return _cnvcState;
            }
            set
            {
                if ((value != _cnvcState))
                {
                    _cnvcState = value;
                    OnPropertyChanged("cnvcState");
                }
            }
        }
    }
}
