//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbProduceLog : Entity
    {
        
        private Decimal _cnnProduceSerialNo;
        
        private String _cnvcProduceDeptID;
        
        private DateTime? _cndProduceDate;
        
        private DateTime? _cndShipBeginDate;
        
        private DateTime? _cndShipEndDate;
        
        private String _cnvcProduceState;
        
        private String _cnvcOperID;
        
        private DateTime? _cndOperDate;
        
        [DataMember()]
        public Decimal cnnProduceSerialNo
        {
            get
            {
                return _cnnProduceSerialNo;
            }
            set
            {
                if ((value != _cnnProduceSerialNo))
                {
                    _cnnProduceSerialNo = value;
                    OnPropertyChanged("cnnProduceSerialNo");
                }
            }
        }
        
        [DataMember()]
        public String cnvcProduceDeptID
        {
            get
            {
                return _cnvcProduceDeptID;
            }
            set
            {
                if ((value != _cnvcProduceDeptID))
                {
                    _cnvcProduceDeptID = value;
                    OnPropertyChanged("cnvcProduceDeptID");
                }
            }
        }
        
        [DataMember()]
        public DateTime? cndProduceDate
        {
            get
            {
                return _cndProduceDate;
            }
            set
            {
                if ((value != _cndProduceDate))
                {
                    _cndProduceDate = value;
                    OnPropertyChanged("cndProduceDate");
                }
            }
        }
        
        [DataMember()]
        public DateTime? cndShipBeginDate
        {
            get
            {
                return _cndShipBeginDate;
            }
            set
            {
                if ((value != _cndShipBeginDate))
                {
                    _cndShipBeginDate = value;
                    OnPropertyChanged("cndShipBeginDate");
                }
            }
        }
        
        [DataMember()]
        public DateTime? cndShipEndDate
        {
            get
            {
                return _cndShipEndDate;
            }
            set
            {
                if ((value != _cndShipEndDate))
                {
                    _cndShipEndDate = value;
                    OnPropertyChanged("cndShipEndDate");
                }
            }
        }
        
        [DataMember()]
        public String cnvcProduceState
        {
            get
            {
                return _cnvcProduceState;
            }
            set
            {
                if ((value != _cnvcProduceState))
                {
                    _cnvcProduceState = value;
                    OnPropertyChanged("cnvcProduceState");
                }
            }
        }
        
        [DataMember()]
        public String cnvcOperID
        {
            get
            {
                return _cnvcOperID;
            }
            set
            {
                if ((value != _cnvcOperID))
                {
                    _cnvcOperID = value;
                    OnPropertyChanged("cnvcOperID");
                }
            }
        }
        
        [DataMember()]
        public DateTime? cndOperDate
        {
            get
            {
                return _cndOperDate;
            }
            set
            {
                if ((value != _cndOperDate))
                {
                    _cndOperDate = value;
                    OnPropertyChanged("cndOperDate");
                }
            }
        }
    }
}
