//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbRepAssCount : Entity
    {
        
        private String _vcDeptID;
        
        private String _vcDate;
        
        private Int32? _NewAss;
        
        private Int32? _LoseAss;
        
        private Int32? _RelaseLoseAss;
        
        private Int32? _OnlyAss;
        
        [DataMember()]
        public String vcDeptID
        {
            get
            {
                return _vcDeptID;
            }
            set
            {
                if ((value != _vcDeptID))
                {
                    _vcDeptID = value;
                    OnPropertyChanged("vcDeptID");
                }
            }
        }
        
        [DataMember()]
        public String vcDate
        {
            get
            {
                return _vcDate;
            }
            set
            {
                if ((value != _vcDate))
                {
                    _vcDate = value;
                    OnPropertyChanged("vcDate");
                }
            }
        }
        
        [DataMember()]
        public Int32? NewAss
        {
            get
            {
                return _NewAss;
            }
            set
            {
                if ((value != _NewAss))
                {
                    _NewAss = value;
                    OnPropertyChanged("NewAss");
                }
            }
        }
        
        [DataMember()]
        public Int32? LoseAss
        {
            get
            {
                return _LoseAss;
            }
            set
            {
                if ((value != _LoseAss))
                {
                    _LoseAss = value;
                    OnPropertyChanged("LoseAss");
                }
            }
        }
        
        [DataMember()]
        public Int32? RelaseLoseAss
        {
            get
            {
                return _RelaseLoseAss;
            }
            set
            {
                if ((value != _RelaseLoseAss))
                {
                    _RelaseLoseAss = value;
                    OnPropertyChanged("RelaseLoseAss");
                }
            }
        }
        
        [DataMember()]
        public Int32? OnlyAss
        {
            get
            {
                return _OnlyAss;
            }
            set
            {
                if ((value != _OnlyAss))
                {
                    _OnlyAss = value;
                    OnPropertyChanged("OnlyAss");
                }
            }
        }
    }
}
