//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbRepAssFill : Entity
    {
        
        private String _vcDeptID;
        
        private String _vcDate;
        
        private Int32 _AssCount;
        
        private Decimal _FillFee;
        
        private Decimal _PromFee;
        
        private Int32 _FillCount;
        
        private String _vcAssBelongDept;
        
        [DataMember()]
        public String vcDeptID
        {
            get
            {
                return _vcDeptID;
            }
            set
            {
                if ((value != _vcDeptID))
                {
                    _vcDeptID = value;
                    OnPropertyChanged("vcDeptID");
                }
            }
        }
        
        [DataMember()]
        public String vcDate
        {
            get
            {
                return _vcDate;
            }
            set
            {
                if ((value != _vcDate))
                {
                    _vcDate = value;
                    OnPropertyChanged("vcDate");
                }
            }
        }
        
        [DataMember()]
        public Int32 AssCount
        {
            get
            {
                return _AssCount;
            }
            set
            {
                if ((value != _AssCount))
                {
                    _AssCount = value;
                    OnPropertyChanged("AssCount");
                }
            }
        }
        
        [DataMember()]
        public Decimal FillFee
        {
            get
            {
                return _FillFee;
            }
            set
            {
                if ((value != _FillFee))
                {
                    _FillFee = value;
                    OnPropertyChanged("FillFee");
                }
            }
        }
        
        [DataMember()]
        public Decimal PromFee
        {
            get
            {
                return _PromFee;
            }
            set
            {
                if ((value != _PromFee))
                {
                    _PromFee = value;
                    OnPropertyChanged("PromFee");
                }
            }
        }
        
        [DataMember()]
        public Int32 FillCount
        {
            get
            {
                return _FillCount;
            }
            set
            {
                if ((value != _FillCount))
                {
                    _FillCount = value;
                    OnPropertyChanged("FillCount");
                }
            }
        }
        
        [DataMember()]
        public String vcAssBelongDept
        {
            get
            {
                return _vcAssBelongDept;
            }
            set
            {
                if ((value != _vcAssBelongDept))
                {
                    _vcAssBelongDept = value;
                    OnPropertyChanged("vcAssBelongDept");
                }
            }
        }
    }
}
