//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbSellDayCheckDetail : Entity
    {
        
        private Decimal _cnnCheckSerialNo;
        
        private String _cnvcProductCode;
        
        private String _cnvcProductName;
        
        private Decimal? _cnnProductPrice;
        
        private String _cnvcUnit;
        
        private Decimal? _cnnOriginalStorage;
        
        private Decimal? _cnnOrderCount;
        
        private Decimal? _cnnMoveOutCount;
        
        private Decimal? _cnnMoveInCount;
        
        private Decimal? _cnnLoseCount;
        
        private Decimal? _cnnFreeCount;
        
        private Decimal? _cnnUseCount;
        
        private Decimal? _cnnSellCount;
        
        private Decimal? _cnnSystemCount;
        
        private Decimal? _cnnRealCount;
        
        private Decimal? _cnnDifferentCount;
        
        private Decimal? _cnnDifferentSum;
        
        private Decimal? _cnnReceiveCount;
        
        [DataMember()]
        public Decimal cnnCheckSerialNo
        {
            get
            {
                return _cnnCheckSerialNo;
            }
            set
            {
                if ((value != _cnnCheckSerialNo))
                {
                    _cnnCheckSerialNo = value;
                    OnPropertyChanged("cnnCheckSerialNo");
                }
            }
        }
        
        [DataMember()]
        public String cnvcProductCode
        {
            get
            {
                return _cnvcProductCode;
            }
            set
            {
                if ((value != _cnvcProductCode))
                {
                    _cnvcProductCode = value;
                    OnPropertyChanged("cnvcProductCode");
                }
            }
        }
        
        [DataMember()]
        public String cnvcProductName
        {
            get
            {
                return _cnvcProductName;
            }
            set
            {
                if ((value != _cnvcProductName))
                {
                    _cnvcProductName = value;
                    OnPropertyChanged("cnvcProductName");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnProductPrice
        {
            get
            {
                return _cnnProductPrice;
            }
            set
            {
                if ((value != _cnnProductPrice))
                {
                    _cnnProductPrice = value;
                    OnPropertyChanged("cnnProductPrice");
                }
            }
        }
        
        [DataMember()]
        public String cnvcUnit
        {
            get
            {
                return _cnvcUnit;
            }
            set
            {
                if ((value != _cnvcUnit))
                {
                    _cnvcUnit = value;
                    OnPropertyChanged("cnvcUnit");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnOriginalStorage
        {
            get
            {
                return _cnnOriginalStorage;
            }
            set
            {
                if ((value != _cnnOriginalStorage))
                {
                    _cnnOriginalStorage = value;
                    OnPropertyChanged("cnnOriginalStorage");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnOrderCount
        {
            get
            {
                return _cnnOrderCount;
            }
            set
            {
                if ((value != _cnnOrderCount))
                {
                    _cnnOrderCount = value;
                    OnPropertyChanged("cnnOrderCount");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnMoveOutCount
        {
            get
            {
                return _cnnMoveOutCount;
            }
            set
            {
                if ((value != _cnnMoveOutCount))
                {
                    _cnnMoveOutCount = value;
                    OnPropertyChanged("cnnMoveOutCount");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnMoveInCount
        {
            get
            {
                return _cnnMoveInCount;
            }
            set
            {
                if ((value != _cnnMoveInCount))
                {
                    _cnnMoveInCount = value;
                    OnPropertyChanged("cnnMoveInCount");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnLoseCount
        {
            get
            {
                return _cnnLoseCount;
            }
            set
            {
                if ((value != _cnnLoseCount))
                {
                    _cnnLoseCount = value;
                    OnPropertyChanged("cnnLoseCount");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnFreeCount
        {
            get
            {
                return _cnnFreeCount;
            }
            set
            {
                if ((value != _cnnFreeCount))
                {
                    _cnnFreeCount = value;
                    OnPropertyChanged("cnnFreeCount");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnUseCount
        {
            get
            {
                return _cnnUseCount;
            }
            set
            {
                if ((value != _cnnUseCount))
                {
                    _cnnUseCount = value;
                    OnPropertyChanged("cnnUseCount");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnSellCount
        {
            get
            {
                return _cnnSellCount;
            }
            set
            {
                if ((value != _cnnSellCount))
                {
                    _cnnSellCount = value;
                    OnPropertyChanged("cnnSellCount");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnSystemCount
        {
            get
            {
                return _cnnSystemCount;
            }
            set
            {
                if ((value != _cnnSystemCount))
                {
                    _cnnSystemCount = value;
                    OnPropertyChanged("cnnSystemCount");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnRealCount
        {
            get
            {
                return _cnnRealCount;
            }
            set
            {
                if ((value != _cnnRealCount))
                {
                    _cnnRealCount = value;
                    OnPropertyChanged("cnnRealCount");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnDifferentCount
        {
            get
            {
                return _cnnDifferentCount;
            }
            set
            {
                if ((value != _cnnDifferentCount))
                {
                    _cnnDifferentCount = value;
                    OnPropertyChanged("cnnDifferentCount");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnDifferentSum
        {
            get
            {
                return _cnnDifferentSum;
            }
            set
            {
                if ((value != _cnnDifferentSum))
                {
                    _cnnDifferentSum = value;
                    OnPropertyChanged("cnnDifferentSum");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnReceiveCount
        {
            get
            {
                return _cnnReceiveCount;
            }
            set
            {
                if ((value != _cnnReceiveCount))
                {
                    _cnnReceiveCount = value;
                    OnPropertyChanged("cnnReceiveCount");
                }
            }
        }
    }
}
