//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbStorage : Entity
    {
        
        private String _cnvcStorageDeptID;
        
        private String _cnvcProductCode;
        
        private String _cnvcProductName;
        
        private String _cnvcUnit;
        
        private Decimal? _cnnCount;
        
        private Decimal? _cnnSafeCount;
        
        private Decimal? _cnnSafeUpCount;
        
        [DataMember()]
        public String cnvcStorageDeptID
        {
            get
            {
                return _cnvcStorageDeptID;
            }
            set
            {
                if ((value != _cnvcStorageDeptID))
                {
                    _cnvcStorageDeptID = value;
                    OnPropertyChanged("cnvcStorageDeptID");
                }
            }
        }
        
        [DataMember()]
        public String cnvcProductCode
        {
            get
            {
                return _cnvcProductCode;
            }
            set
            {
                if ((value != _cnvcProductCode))
                {
                    _cnvcProductCode = value;
                    OnPropertyChanged("cnvcProductCode");
                }
            }
        }
        
        [DataMember()]
        public String cnvcProductName
        {
            get
            {
                return _cnvcProductName;
            }
            set
            {
                if ((value != _cnvcProductName))
                {
                    _cnvcProductName = value;
                    OnPropertyChanged("cnvcProductName");
                }
            }
        }
        
        [DataMember()]
        public String cnvcUnit
        {
            get
            {
                return _cnvcUnit;
            }
            set
            {
                if ((value != _cnvcUnit))
                {
                    _cnvcUnit = value;
                    OnPropertyChanged("cnvcUnit");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnCount
        {
            get
            {
                return _cnnCount;
            }
            set
            {
                if ((value != _cnnCount))
                {
                    _cnnCount = value;
                    OnPropertyChanged("cnnCount");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnSafeCount
        {
            get
            {
                return _cnnSafeCount;
            }
            set
            {
                if ((value != _cnnSafeCount))
                {
                    _cnnSafeCount = value;
                    OnPropertyChanged("cnnSafeCount");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnSafeUpCount
        {
            get
            {
                return _cnnSafeUpCount;
            }
            set
            {
                if ((value != _cnnSafeUpCount))
                {
                    _cnnSafeUpCount = value;
                    OnPropertyChanged("cnnSafeUpCount");
                }
            }
        }
    }
}
