//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbStockMainLog : Entity
    {
        
        private Int64 _cnnId;
        
        private Int64 _cnnMainId;
        
        private String _cnvcSupplierCode;
        
        private String _cnvcWhCode;
        
        private String _cnvcDeptId;
        
        private Int32 _cnnOperType;
        
        private Int64 _cnnSource;
        
        private DateTime _cndCreateDate;
        
        private String _cnvcCreaterId;
        
        private String _cnvcCreaterName;
        
        private DateTime? _cndModifyDate;
        
        private String _cnvcModifier;
        
        private String _cnvcModifierName;
        
        private DateTime? _cndCheckDate;
        
        private String _cnvcCheckerId;
        
        private String _cnvcCheckerName;
        
        private DateTime _cndBusinessDate;
        
        private Int32 _cnnYear;
        
        private Int32 _cnnMonth;
        
        private Int32 _cnnStatus;
        
        private String _cnvcComments;
        
        private Int32 _cnnDirection;
        
        [DataMember()]
        public Int64 cnnId
        {
            get
            {
                return _cnnId;
            }
            set
            {
                if ((value != _cnnId))
                {
                    _cnnId = value;
                    OnPropertyChanged("cnnId");
                }
            }
        }
        
        [DataMember()]
        public Int64 cnnMainId
        {
            get
            {
                return _cnnMainId;
            }
            set
            {
                if ((value != _cnnMainId))
                {
                    _cnnMainId = value;
                    OnPropertyChanged("cnnMainId");
                }
            }
        }
        
        [DataMember()]
        public String cnvcSupplierCode
        {
            get
            {
                return _cnvcSupplierCode;
            }
            set
            {
                if ((value != _cnvcSupplierCode))
                {
                    _cnvcSupplierCode = value;
                    OnPropertyChanged("cnvcSupplierCode");
                }
            }
        }
        
        [DataMember()]
        public String cnvcWhCode
        {
            get
            {
                return _cnvcWhCode;
            }
            set
            {
                if ((value != _cnvcWhCode))
                {
                    _cnvcWhCode = value;
                    OnPropertyChanged("cnvcWhCode");
                }
            }
        }
        
        [DataMember()]
        public String cnvcDeptId
        {
            get
            {
                return _cnvcDeptId;
            }
            set
            {
                if ((value != _cnvcDeptId))
                {
                    _cnvcDeptId = value;
                    OnPropertyChanged("cnvcDeptId");
                }
            }
        }
        
        [DataMember()]
        public Int32 cnnOperType
        {
            get
            {
                return _cnnOperType;
            }
            set
            {
                if ((value != _cnnOperType))
                {
                    _cnnOperType = value;
                    OnPropertyChanged("cnnOperType");
                }
            }
        }
        
        [DataMember()]
        public Int64 cnnSource
        {
            get
            {
                return _cnnSource;
            }
            set
            {
                if ((value != _cnnSource))
                {
                    _cnnSource = value;
                    OnPropertyChanged("cnnSource");
                }
            }
        }
        
        [DataMember()]
        public DateTime cndCreateDate
        {
            get
            {
                return _cndCreateDate;
            }
            set
            {
                if ((value != _cndCreateDate))
                {
                    _cndCreateDate = value;
                    OnPropertyChanged("cndCreateDate");
                }
            }
        }
        
        [DataMember()]
        public String cnvcCreaterId
        {
            get
            {
                return _cnvcCreaterId;
            }
            set
            {
                if ((value != _cnvcCreaterId))
                {
                    _cnvcCreaterId = value;
                    OnPropertyChanged("cnvcCreaterId");
                }
            }
        }
        
        [DataMember()]
        public String cnvcCreaterName
        {
            get
            {
                return _cnvcCreaterName;
            }
            set
            {
                if ((value != _cnvcCreaterName))
                {
                    _cnvcCreaterName = value;
                    OnPropertyChanged("cnvcCreaterName");
                }
            }
        }
        
        [DataMember()]
        public DateTime? cndModifyDate
        {
            get
            {
                return _cndModifyDate;
            }
            set
            {
                if ((value != _cndModifyDate))
                {
                    _cndModifyDate = value;
                    OnPropertyChanged("cndModifyDate");
                }
            }
        }
        
        [DataMember()]
        public String cnvcModifier
        {
            get
            {
                return _cnvcModifier;
            }
            set
            {
                if ((value != _cnvcModifier))
                {
                    _cnvcModifier = value;
                    OnPropertyChanged("cnvcModifier");
                }
            }
        }
        
        [DataMember()]
        public String cnvcModifierName
        {
            get
            {
                return _cnvcModifierName;
            }
            set
            {
                if ((value != _cnvcModifierName))
                {
                    _cnvcModifierName = value;
                    OnPropertyChanged("cnvcModifierName");
                }
            }
        }
        
        [DataMember()]
        public DateTime? cndCheckDate
        {
            get
            {
                return _cndCheckDate;
            }
            set
            {
                if ((value != _cndCheckDate))
                {
                    _cndCheckDate = value;
                    OnPropertyChanged("cndCheckDate");
                }
            }
        }
        
        [DataMember()]
        public String cnvcCheckerId
        {
            get
            {
                return _cnvcCheckerId;
            }
            set
            {
                if ((value != _cnvcCheckerId))
                {
                    _cnvcCheckerId = value;
                    OnPropertyChanged("cnvcCheckerId");
                }
            }
        }
        
        [DataMember()]
        public String cnvcCheckerName
        {
            get
            {
                return _cnvcCheckerName;
            }
            set
            {
                if ((value != _cnvcCheckerName))
                {
                    _cnvcCheckerName = value;
                    OnPropertyChanged("cnvcCheckerName");
                }
            }
        }
        
        [DataMember()]
        public DateTime cndBusinessDate
        {
            get
            {
                return _cndBusinessDate;
            }
            set
            {
                if ((value != _cndBusinessDate))
                {
                    _cndBusinessDate = value;
                    OnPropertyChanged("cndBusinessDate");
                }
            }
        }
        
        [DataMember()]
        public Int32 cnnYear
        {
            get
            {
                return _cnnYear;
            }
            set
            {
                if ((value != _cnnYear))
                {
                    _cnnYear = value;
                    OnPropertyChanged("cnnYear");
                }
            }
        }
        
        [DataMember()]
        public Int32 cnnMonth
        {
            get
            {
                return _cnnMonth;
            }
            set
            {
                if ((value != _cnnMonth))
                {
                    _cnnMonth = value;
                    OnPropertyChanged("cnnMonth");
                }
            }
        }
        
        [DataMember()]
        public Int32 cnnStatus
        {
            get
            {
                return _cnnStatus;
            }
            set
            {
                if ((value != _cnnStatus))
                {
                    _cnnStatus = value;
                    OnPropertyChanged("cnnStatus");
                }
            }
        }
        
        [DataMember()]
        public String cnvcComments
        {
            get
            {
                return _cnvcComments;
            }
            set
            {
                if ((value != _cnvcComments))
                {
                    _cnvcComments = value;
                    OnPropertyChanged("cnvcComments");
                }
            }
        }
        
        [DataMember()]
        public Int32 cnnDirection
        {
            get
            {
                return _cnnDirection;
            }
            set
            {
                if ((value != _cnnDirection))
                {
                    _cnnDirection = value;
                    OnPropertyChanged("cnnDirection");
                }
            }
        }
    }
}
