//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbStockPlan : Entity
    {
        
        private String _cnvcProductCode;
        
        private String _cnvcProductName;
        
        private Decimal? _cnnPlanCount;
        
        private String _cnvcUnit;
        
        private String _cnvcMonth;
        
        private DateTime? _cndStartDate1;
        
        private Decimal? _cnnCount1;
        
        private Decimal? _cnnSumFee1;
        
        private DateTime? _cndStartDate2;
        
        private Decimal? _cnnCount2;
        
        private Decimal? _cnnSumFee2;
        
        private DateTime? _cndStartDate3;
        
        private Decimal? _cnnCount3;
        
        private Decimal? _cnnSumFee3;
        
        private DateTime? _cndStartDate4;
        
        private Decimal? _cnnCount4;
        
        private Decimal? _cnnSumFee4;
        
        private Decimal? _cnnSumFee;
        
        [DataMember()]
        public String cnvcProductCode
        {
            get
            {
                return _cnvcProductCode;
            }
            set
            {
                if ((value != _cnvcProductCode))
                {
                    _cnvcProductCode = value;
                    OnPropertyChanged("cnvcProductCode");
                }
            }
        }
        
        [DataMember()]
        public String cnvcProductName
        {
            get
            {
                return _cnvcProductName;
            }
            set
            {
                if ((value != _cnvcProductName))
                {
                    _cnvcProductName = value;
                    OnPropertyChanged("cnvcProductName");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnPlanCount
        {
            get
            {
                return _cnnPlanCount;
            }
            set
            {
                if ((value != _cnnPlanCount))
                {
                    _cnnPlanCount = value;
                    OnPropertyChanged("cnnPlanCount");
                }
            }
        }
        
        [DataMember()]
        public String cnvcUnit
        {
            get
            {
                return _cnvcUnit;
            }
            set
            {
                if ((value != _cnvcUnit))
                {
                    _cnvcUnit = value;
                    OnPropertyChanged("cnvcUnit");
                }
            }
        }
        
        [DataMember()]
        public String cnvcMonth
        {
            get
            {
                return _cnvcMonth;
            }
            set
            {
                if ((value != _cnvcMonth))
                {
                    _cnvcMonth = value;
                    OnPropertyChanged("cnvcMonth");
                }
            }
        }
        
        [DataMember()]
        public DateTime? cndStartDate1
        {
            get
            {
                return _cndStartDate1;
            }
            set
            {
                if ((value != _cndStartDate1))
                {
                    _cndStartDate1 = value;
                    OnPropertyChanged("cndStartDate1");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnCount1
        {
            get
            {
                return _cnnCount1;
            }
            set
            {
                if ((value != _cnnCount1))
                {
                    _cnnCount1 = value;
                    OnPropertyChanged("cnnCount1");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnSumFee1
        {
            get
            {
                return _cnnSumFee1;
            }
            set
            {
                if ((value != _cnnSumFee1))
                {
                    _cnnSumFee1 = value;
                    OnPropertyChanged("cnnSumFee1");
                }
            }
        }
        
        [DataMember()]
        public DateTime? cndStartDate2
        {
            get
            {
                return _cndStartDate2;
            }
            set
            {
                if ((value != _cndStartDate2))
                {
                    _cndStartDate2 = value;
                    OnPropertyChanged("cndStartDate2");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnCount2
        {
            get
            {
                return _cnnCount2;
            }
            set
            {
                if ((value != _cnnCount2))
                {
                    _cnnCount2 = value;
                    OnPropertyChanged("cnnCount2");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnSumFee2
        {
            get
            {
                return _cnnSumFee2;
            }
            set
            {
                if ((value != _cnnSumFee2))
                {
                    _cnnSumFee2 = value;
                    OnPropertyChanged("cnnSumFee2");
                }
            }
        }
        
        [DataMember()]
        public DateTime? cndStartDate3
        {
            get
            {
                return _cndStartDate3;
            }
            set
            {
                if ((value != _cndStartDate3))
                {
                    _cndStartDate3 = value;
                    OnPropertyChanged("cndStartDate3");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnCount3
        {
            get
            {
                return _cnnCount3;
            }
            set
            {
                if ((value != _cnnCount3))
                {
                    _cnnCount3 = value;
                    OnPropertyChanged("cnnCount3");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnSumFee3
        {
            get
            {
                return _cnnSumFee3;
            }
            set
            {
                if ((value != _cnnSumFee3))
                {
                    _cnnSumFee3 = value;
                    OnPropertyChanged("cnnSumFee3");
                }
            }
        }
        
        [DataMember()]
        public DateTime? cndStartDate4
        {
            get
            {
                return _cndStartDate4;
            }
            set
            {
                if ((value != _cndStartDate4))
                {
                    _cndStartDate4 = value;
                    OnPropertyChanged("cndStartDate4");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnCount4
        {
            get
            {
                return _cnnCount4;
            }
            set
            {
                if ((value != _cnnCount4))
                {
                    _cnnCount4 = value;
                    OnPropertyChanged("cnnCount4");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnSumFee4
        {
            get
            {
                return _cnnSumFee4;
            }
            set
            {
                if ((value != _cnnSumFee4))
                {
                    _cnnSumFee4 = value;
                    OnPropertyChanged("cnnSumFee4");
                }
            }
        }
        
        [DataMember()]
        public Decimal? cnnSumFee
        {
            get
            {
                return _cnnSumFee;
            }
            set
            {
                if ((value != _cnnSumFee))
                {
                    _cnnSumFee = value;
                    OnPropertyChanged("cnnSumFee");
                }
            }
        }
    }
}
