//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Models
{
    using System;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [DataContract()]
    public class tbWarehouse : Entity
    {
        
        private String _cnvcWhCode;
        
        private String _cnvcWhName;
        
        private String _cnvcDepID;
        
        private String _cnvcWhAddress;
        
        private String _cnvcWhPhone;
        
        private String _cnvcWhPerson;
        
        private String _cnvcWhComments;
        
        private Boolean _cnbInvalid;
        
        [DataMember()]
        public String cnvcWhCode
        {
            get
            {
                return _cnvcWhCode;
            }
            set
            {
                if ((value != _cnvcWhCode))
                {
                    _cnvcWhCode = value;
                    OnPropertyChanged("cnvcWhCode");
                }
            }
        }
        
        [DataMember()]
        public String cnvcWhName
        {
            get
            {
                return _cnvcWhName;
            }
            set
            {
                if ((value != _cnvcWhName))
                {
                    _cnvcWhName = value;
                    OnPropertyChanged("cnvcWhName");
                }
            }
        }
        
        [DataMember()]
        public String cnvcDepID
        {
            get
            {
                return _cnvcDepID;
            }
            set
            {
                if ((value != _cnvcDepID))
                {
                    _cnvcDepID = value;
                    OnPropertyChanged("cnvcDepID");
                }
            }
        }
        
        [DataMember()]
        public String cnvcWhAddress
        {
            get
            {
                return _cnvcWhAddress;
            }
            set
            {
                if ((value != _cnvcWhAddress))
                {
                    _cnvcWhAddress = value;
                    OnPropertyChanged("cnvcWhAddress");
                }
            }
        }
        
        [DataMember()]
        public String cnvcWhPhone
        {
            get
            {
                return _cnvcWhPhone;
            }
            set
            {
                if ((value != _cnvcWhPhone))
                {
                    _cnvcWhPhone = value;
                    OnPropertyChanged("cnvcWhPhone");
                }
            }
        }
        
        [DataMember()]
        public String cnvcWhPerson
        {
            get
            {
                return _cnvcWhPerson;
            }
            set
            {
                if ((value != _cnvcWhPerson))
                {
                    _cnvcWhPerson = value;
                    OnPropertyChanged("cnvcWhPerson");
                }
            }
        }
        
        [DataMember()]
        public String cnvcWhComments
        {
            get
            {
                return _cnvcWhComments;
            }
            set
            {
                if ((value != _cnvcWhComments))
                {
                    _cnvcWhComments = value;
                    OnPropertyChanged("cnvcWhComments");
                }
            }
        }
        
        [DataMember()]
        public Boolean cnbInvalid
        {
            get
            {
                return _cnbInvalid;
            }
            set
            {
                if ((value != _cnbInvalid))
                {
                    _cnbInvalid = value;
                    OnPropertyChanged("cnbInvalid");
                }
            }
        }
    }
}
