//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data.Entity.ModelConfiguration;
    using DXInfo.Models;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public class aspnet_ApplicationsConfiguration : EntityTypeConfiguration<aspnet_Applications>
    {
        
        public aspnet_ApplicationsConfiguration()
        {
            this.HasKey(k => k.ApplicationId);
            this.Property(o => o.ApplicationId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            this.Property(o => o.ApplicationName).IsRequired();
            this.Property(o => o.ApplicationName).IsUnicode();
            this.Property(o => o.ApplicationName).HasMaxLength(256);
            this.Property(o => o.LoweredApplicationName).IsRequired();
            this.Property(o => o.LoweredApplicationName).IsUnicode();
            this.Property(o => o.LoweredApplicationName).HasMaxLength(256);
            this.Property(o => o.ApplicationId).IsRequired();
            this.Property(o => o.Description).IsUnicode();
            this.Property(o => o.Description).HasMaxLength(256);
        }
    }
}
