//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data.Entity.ModelConfiguration;
    using DXInfo.Models;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public class CheckDifferencesConfiguration : EntityTypeConfiguration<CheckDifferences>
    {
        
        public CheckDifferencesConfiguration()
        {
            this.HasKey(k => k.Id);
            this.Property(o => o.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            this.Property(o => o.Id).IsRequired();
            this.Property(o => o.DeptId).IsRequired();
            this.Property(o => o.UserId).IsRequired();
            this.Property(o => o.Amount).HasPrecision(24,2);
            this.Property(o => o.Amount).IsRequired();
            this.Property(o => o.More).HasPrecision(24,2);
            this.Property(o => o.More).IsRequired();
            this.Property(o => o.Less).HasPrecision(24,2);
            this.Property(o => o.Less).IsRequired();
            this.Property(o => o.DifDate).IsRequired();
            this.Property(o => o.OperUserId).IsRequired();
            this.Property(o => o.OperDeptId).IsRequired();
            this.Property(o => o.CreateDate).IsRequired();
            this.Property(o => o.Comment).IsUnicode();
            this.Property(o => o.Comment).HasMaxLength(200);
        }
    }
}
