//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data.Entity.ModelConfiguration;
    using DXInfo.Models;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public class ConsumeConfiguration : EntityTypeConfiguration<Consume>
    {
        
        public ConsumeConfiguration()
        {
            this.HasKey(k => k.Id);
            this.Property(o => o.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            this.Property(o => o.Id).IsRequired();
            this.Property(o => o.LastBalance).HasPrecision(24,2);
            this.Property(o => o.LastBalance).IsRequired();
            this.Property(o => o.Sum).HasPrecision(24,2);
            this.Property(o => o.Sum).IsRequired();
            this.Property(o => o.PayVoucher).HasPrecision(24,2);
            this.Property(o => o.PayVoucher).IsRequired();
            this.Property(o => o.Voucher).HasPrecision(24,2);
            this.Property(o => o.Voucher).IsRequired();
            this.Property(o => o.Discount).HasPrecision(24,2);
            this.Property(o => o.Discount).IsRequired();
            this.Property(o => o.Amount).HasPrecision(24,2);
            this.Property(o => o.Amount).IsRequired();
            this.Property(o => o.Point).HasPrecision(24,2);
            this.Property(o => o.Point).IsRequired();
            this.Property(o => o.Balance).HasPrecision(24,2);
            this.Property(o => o.Balance).IsRequired();
            this.Property(o => o.Cash).HasPrecision(24,2);
            this.Property(o => o.Cash).IsRequired();
            this.Property(o => o.Change).HasPrecision(24,2);
            this.Property(o => o.Change).IsRequired();
            this.Property(o => o.CreateDate).IsRequired();
            this.Property(o => o.UserId).IsRequired();
            this.Property(o => o.DeptId).IsRequired();
            this.Property(o => o.ConsumeType).IsRequired();
            this.Property(o => o.DeskNo).IsUnicode();
            this.Property(o => o.DeskNo).HasMaxLength(50);
            this.Property(o => o.Quantity).HasPrecision(24,2);
            this.Property(o => o.Quantity).IsRequired();
            this.Property(o => o.SourceType).IsRequired();
            this.Property(o => o.IsValid).IsRequired();
            this.Property(o => o.Sn).HasMaxLength(200);
            this.Property(o => o.OperatorsOnDuty).HasMaxLength(200);
        }
    }
}
