//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data.Entity.ModelConfiguration;
    using DXInfo.Models;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public class DeptsConfiguration : EntityTypeConfiguration<Depts>
    {
        
        public DeptsConfiguration()
        {
            this.HasKey(k => k.DeptId);
            this.Property(o => o.DeptId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            this.Property(o => o.DeptId).IsRequired();
            this.Property(o => o.Address).IsUnicode();
            this.Property(o => o.Address).HasMaxLength(2000);
            this.Property(o => o.DeptCode).IsRequired();
            this.Property(o => o.DeptCode).IsUnicode();
            this.Property(o => o.DeptCode).HasMaxLength(256);
            this.Property(o => o.DeptName).IsRequired();
            this.Property(o => o.DeptName).IsUnicode();
            this.Property(o => o.DeptName).HasMaxLength(256);
            this.Property(o => o.Comment).IsUnicode();
            this.Property(o => o.Comment).HasMaxLength(200);
            this.Property(o => o.IsDeptPrice).IsRequired();
            this.Property(o => o.DeptType).IsRequired();
        }
    }
}
