//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data.Entity.ModelConfiguration;
    using DXInfo.Models;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public class schema_infoConfiguration : EntityTypeConfiguration<schema_info>
    {
        
        public schema_infoConfiguration()
        {
            this.HasKey(k => new { k.schema_major_version,k.schema_minor_version });
            this.Property(o => o.schema_major_version).IsRequired();
            this.Property(o => o.schema_minor_version).IsRequired();
            this.Property(o => o.schema_extended_info).IsRequired();
            this.Property(o => o.schema_extended_info).IsUnicode();
            this.Property(o => o.schema_extended_info).HasMaxLength(100);
        }
    }
}
