//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data.Entity.ModelConfiguration;
    using DXInfo.Models;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public class scope_infoConfiguration : EntityTypeConfiguration<scope_info>
    {
        
        public scope_infoConfiguration()
        {
            this.HasKey(k => k.sync_scope_name);
            this.Property(o => o.scope_local_id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            this.Property(o => o.scope_local_id).IsRequired();
            this.Property(o => o.scope_id).IsRequired();
            this.Property(o => o.sync_scope_name).IsRequired();
            this.Property(o => o.sync_scope_name).IsUnicode();
            this.Property(o => o.sync_scope_name).HasMaxLength(100);
            this.Property(o => o.scope_restore_count).IsRequired();
            this.Property(o => o.scope_user_comment).IsUnicode();
        }
    }
}
