//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data.Entity.ModelConfiguration;
    using DXInfo.Models;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public class tbBillOfMaterialsConfiguration : EntityTypeConfiguration<tbBillOfMaterials>
    {
        
        public tbBillOfMaterialsConfiguration()
        {
            this.HasKey(k => new { k.cnvcPartInvCode,k.cnvcComponentInvCode });
            this.Property(o => o.cnvcPartInvCode).IsRequired();
            this.Property(o => o.cnvcPartInvCode).HasMaxLength(20);
            this.Property(o => o.cnvcComponentInvCode).IsRequired();
            this.Property(o => o.cnvcComponentInvCode).HasMaxLength(20);
            this.Property(o => o.cnnBaseQtyN).HasPrecision(10,2);
            this.Property(o => o.cnnBaseQtyN).IsRequired();
            this.Property(o => o.cnnBaseQtyD).HasPrecision(10,2);
            this.Property(o => o.cnnBaseQtyD).IsRequired();
        }
    }
}
