//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data.Entity.ModelConfiguration;
    using DXInfo.Models;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public class tbCheckSerialConfiguration : EntityTypeConfiguration<tbCheckSerial>
    {
        
        public tbCheckSerialConfiguration()
        {
            this.HasKey(k => new { k.cnnSerialNo,k.cnvcCode });
            this.Property(o => o.cnnSerialNo).IsRequired();
            this.Property(o => o.cnvcName).IsRequired();
            this.Property(o => o.cnvcName).HasMaxLength(200);
            this.Property(o => o.cnvcCode).IsRequired();
            this.Property(o => o.cnvcCode).HasMaxLength(20);
            this.Property(o => o.cnnCount).IsRequired();
            this.Property(o => o.cnnAddCount).IsRequired();
            this.Property(o => o.cnnReduceCount).IsRequired();
            this.Property(o => o.cndCreateDate).IsRequired();
            this.Property(o => o.cnvcDeptID).IsRequired();
            this.Property(o => o.cnvcDeptID).HasMaxLength(20);
            this.Property(o => o.cnvcOperID).IsRequired();
            this.Property(o => o.cnvcOperID).HasMaxLength(20);
            this.Property(o => o.cnvcComments).HasMaxLength(200);
        }
    }
}
