//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data.Entity.ModelConfiguration;
    using DXInfo.Models;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public class tbComputationUnitConfiguration : EntityTypeConfiguration<tbComputationUnit>
    {
        
        public tbComputationUnitConfiguration()
        {
            this.HasKey(k => k.cnvcComunitCode);
            this.Property(o => o.cnvcComunitCode).IsRequired();
            this.Property(o => o.cnvcComunitCode).HasMaxLength(10);
            this.Property(o => o.cnvcComUnitName).IsRequired();
            this.Property(o => o.cnvcComUnitName).HasMaxLength(20);
            this.Property(o => o.cnvcGroupCode).IsRequired();
            this.Property(o => o.cnvcGroupCode).HasMaxLength(10);
            this.Property(o => o.cnbMainUnit).IsRequired();
            this.Property(o => o.cniChangRate).HasPrecision(24,9);
            this.Property(o => o.cniChangRate).IsRequired();
        }
    }
}
