//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data.Entity.ModelConfiguration;
    using DXInfo.Models;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public class tbFuncConfiguration : EntityTypeConfiguration<tbFunc>
    {
        
        public tbFuncConfiguration()
        {
            this.HasKey(k => k.cnvcFuncName);
            this.Property(o => o.cnvcFuncName).IsRequired();
            this.Property(o => o.cnvcFuncName).HasMaxLength(30);
            this.Property(o => o.cnvcFuncParentName).IsRequired();
            this.Property(o => o.cnvcFuncParentName).HasMaxLength(30);
            this.Property(o => o.cnvcFuncAddress).HasMaxLength(200);
            this.Property(o => o.cnvcFuncType).IsRequired();
            this.Property(o => o.cnvcFuncType).HasMaxLength(20);
        }
    }
}
