//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data.Entity.ModelConfiguration;
    using DXInfo.Models;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public class tbInventoryConfiguration : EntityTypeConfiguration<tbInventory>
    {
        
        public tbInventoryConfiguration()
        {
            this.HasKey(k => k.cnvcInvCode);
            this.Property(o => o.cnbProductBill).IsRequired();
            this.Property(o => o.cnvcInvCode).IsRequired();
            this.Property(o => o.cnvcInvCode).HasMaxLength(20);
            this.Property(o => o.cnvcInvName).IsRequired();
            this.Property(o => o.cnvcInvName).HasMaxLength(60);
            this.Property(o => o.cnvcInvStd).HasMaxLength(60);
            this.Property(o => o.cnvcInvCCode).HasMaxLength(20);
            this.Property(o => o.cnbSale).IsRequired();
            this.Property(o => o.cnbPurchase).IsRequired();
            this.Property(o => o.cnbSelf).IsRequired();
            this.Property(o => o.cnbComsume).IsRequired();
            this.Property(o => o.cniInvCCost).HasPrecision(10,4);
            this.Property(o => o.cniInvNCost).HasPrecision(20,4);
            this.Property(o => o.cniSafeNum).HasPrecision(10,4);
            this.Property(o => o.cniLowSum).HasPrecision(10,4);
            this.Property(o => o.cnvcCreatePerson).HasMaxLength(20);
            this.Property(o => o.cnvcModifyPerson).HasMaxLength(20);
            this.Property(o => o.cnvcValueType).HasMaxLength(20);
            this.Property(o => o.cnvcGroupCode).HasMaxLength(10);
            this.Property(o => o.cnvcComUnitCode).HasMaxLength(10);
            this.Property(o => o.cnvcSAComUnitCode).HasMaxLength(10);
            this.Property(o => o.cnvcPUComUnitCode).HasMaxLength(10);
            this.Property(o => o.cnvcSTComUnitCode).HasMaxLength(10);
            this.Property(o => o.cnvcProduceUnitCode).HasMaxLength(10);
            this.Property(o => o.cnfRetailPrice).HasPrecision(10,4);
            this.Property(o => o.cnvcShopUnitCode).HasMaxLength(10);
            this.Property(o => o.cnnExpire).IsRequired();
            this.Property(o => o.cnnDue).IsRequired();
        }
    }
}
