//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data.Entity.ModelConfiguration;
    using DXInfo.Models;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public class tbOperConfiguration : EntityTypeConfiguration<tbOper>
    {
        
        public tbOperConfiguration()
        {
            this.HasKey(k => k.vcOperID);
            this.Property(o => o.vcOperID).IsRequired();
            this.Property(o => o.vcOperID).HasMaxLength(10);
            this.Property(o => o.vcOperName).IsRequired();
            this.Property(o => o.vcOperName).HasMaxLength(10);
            this.Property(o => o.vcLimit).HasMaxLength(5);
            this.Property(o => o.vcPwd).HasMaxLength(6);
            this.Property(o => o.vcDeptID).HasMaxLength(5);
            this.Property(o => o.vcActiveFlag).HasMaxLength(5);
            this.Property(o => o.vcPwdBeginFlag).IsUnicode();
            this.Property(o => o.vcPwdBeginFlag).HasMaxLength(5);
        }
    }
}
