//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data.Entity.ModelConfiguration;
    using DXInfo.Models;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public class tbProduceDetailAddConfiguration : EntityTypeConfiguration<tbProduceDetailAdd>
    {
        
        public tbProduceDetailAddConfiguration()
        {
            this.HasKey(k => new { k.cnnProduceSerialNo,k.cnnAddSerialNo,k.cnvcCode });
            this.Property(o => o.cnnProduceSerialNo).IsRequired();
            this.Property(o => o.cnnAddSerialNo).IsRequired();
            this.Property(o => o.cnvcCode).IsRequired();
            this.Property(o => o.cnvcCode).HasMaxLength(20);
            this.Property(o => o.cnvcName).HasMaxLength(20);
            this.Property(o => o.cnvcUnit).HasMaxLength(20);
            this.Property(o => o.cnvcState).HasMaxLength(20);
        }
    }
}
