//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data.Entity.ModelConfiguration;
    using DXInfo.Models;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public class tbStockPlanConfiguration : EntityTypeConfiguration<tbStockPlan>
    {
        
        public tbStockPlanConfiguration()
        {
            this.HasKey(k => new { k.cnvcProductCode,k.cnvcMonth });
            this.Property(o => o.cnvcProductCode).IsRequired();
            this.Property(o => o.cnvcProductCode).HasMaxLength(20);
            this.Property(o => o.cnvcProductName).HasMaxLength(20);
            this.Property(o => o.cnnPlanCount).HasPrecision(10,2);
            this.Property(o => o.cnvcUnit).HasMaxLength(20);
            this.Property(o => o.cnvcMonth).IsRequired();
            this.Property(o => o.cnvcMonth).HasMaxLength(6);
            this.Property(o => o.cnnCount1).HasPrecision(10,2);
            this.Property(o => o.cnnSumFee1).HasPrecision(10,2);
            this.Property(o => o.cnnCount2).HasPrecision(10,2);
            this.Property(o => o.cnnSumFee2).HasPrecision(10,2);
            this.Property(o => o.cnnCount3).HasPrecision(10,2);
            this.Property(o => o.cnnSumFee3).HasPrecision(10,2);
            this.Property(o => o.cnnCount4).HasPrecision(10,2);
            this.Property(o => o.cnnSumFee4).HasPrecision(10,2);
            this.Property(o => o.cnnSumFee).HasPrecision(10,2);
        }
    }
}
