//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data.Entity.ModelConfiguration;
    using DXInfo.Models;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public class tbStockDetailConfiguration : EntityTypeConfiguration<tbStockDetail>
    {
        
        public tbStockDetailConfiguration()
        {
            this.HasKey(k => k.cnnDetailId);
            this.Property(o => o.cnnDetailId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            this.Property(o => o.cnnDetailId).IsRequired();
            this.Property(o => o.cnnMainId).IsRequired();
            this.Property(o => o.cnvcInvCode).IsRequired();
            this.Property(o => o.cnvcInvCode).IsUnicode();
            this.Property(o => o.cnvcInvCode).HasMaxLength(50);
            this.Property(o => o.cnvcComUnitCode).IsRequired();
            this.Property(o => o.cnvcComUnitCode).IsUnicode();
            this.Property(o => o.cnvcComUnitCode).HasMaxLength(50);
            this.Property(o => o.cnnQuantity).HasPrecision(24,9);
            this.Property(o => o.cnnQuantity).IsRequired();
            this.Property(o => o.cnvcMainComUnitCode).IsRequired();
            this.Property(o => o.cnvcMainComUnitCode).IsUnicode();
            this.Property(o => o.cnvcMainComUnitCode).HasMaxLength(50);
            this.Property(o => o.cnnMainQuantity).HasPrecision(24,9);
            this.Property(o => o.cnnMainQuantity).IsRequired();
            this.Property(o => o.cnnPrice).HasPrecision(24,9);
            this.Property(o => o.cnnPrice).IsRequired();
            this.Property(o => o.cnnAmount).HasPrecision(24,9);
            this.Property(o => o.cnnAmount).IsRequired();
            this.Property(o => o.cndOperDate).IsRequired();
            this.Property(o => o.cnvcOper).IsRequired();
            this.Property(o => o.cnvcOper).IsUnicode();
            this.Property(o => o.cnvcOper).HasMaxLength(50);
            this.Property(o => o.cnvcOperName).IsRequired();
            this.Property(o => o.cnvcOperName).IsUnicode();
            this.Property(o => o.cnvcOperName).HasMaxLength(200);
        }
    }
}
