//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data.Entity.ModelConfiguration;
    using DXInfo.Models;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public class tbWarehouseConfiguration : EntityTypeConfiguration<tbWarehouse>
    {
        
        public tbWarehouseConfiguration()
        {
            this.HasKey(k => k.cnvcWhCode);
            this.Property(o => o.cnvcWhCode).IsRequired();
            this.Property(o => o.cnvcWhCode).IsUnicode();
            this.Property(o => o.cnvcWhCode).HasMaxLength(40);
            this.Property(o => o.cnvcWhName).IsRequired();
            this.Property(o => o.cnvcWhName).IsUnicode();
            this.Property(o => o.cnvcWhName).HasMaxLength(20);
            this.Property(o => o.cnvcDepID).IsRequired();
            this.Property(o => o.cnvcDepID).IsUnicode();
            this.Property(o => o.cnvcDepID).HasMaxLength(20);
            this.Property(o => o.cnvcWhAddress).IsUnicode();
            this.Property(o => o.cnvcWhAddress).HasMaxLength(30);
            this.Property(o => o.cnvcWhPhone).IsUnicode();
            this.Property(o => o.cnvcWhPhone).HasMaxLength(20);
            this.Property(o => o.cnvcWhPerson).IsUnicode();
            this.Property(o => o.cnvcWhPerson).HasMaxLength(10);
            this.Property(o => o.cnvcWhComments).IsUnicode();
            this.Property(o => o.cnvcWhComments).HasMaxLength(200);
            this.Property(o => o.cnbInvalid).IsRequired();
        }
    }
}
