//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXInfo.Data.Configuration
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data.Entity.ModelConfiguration;
    using DXInfo.Models;
    using System.ComponentModel.DataAnnotations.Schema;
    
    
    public class TransportsLogConfiguration : EntityTypeConfiguration<TransportsLog>
    {
        
        public TransportsLogConfiguration()
        {
            this.HasKey(k => k.Id);
            this.Property(o => o.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            this.Property(o => o.Id).IsRequired();
            this.Property(o => o.tpId).IsRequired();
            this.Property(o => o.Card).IsRequired();
            this.Property(o => o.InFactory_Date).IsRequired();
            this.Property(o => o.InFactory_UserId).IsRequired();
            this.Property(o => o.InFactory_DeptId).IsRequired();
            this.Property(o => o.Load_Quantity).HasPrecision(18,3);
            this.Property(o => o.Shipment_Quantity).HasPrecision(18,3);
            this.Property(o => o.Shipment_CheckUser).IsUnicode();
            this.Property(o => o.Shipment_CheckUser).HasMaxLength(200);
            this.Property(o => o.AgreeFreightRate).HasPrecision(18,3);
            this.Property(o => o.FreightRate).HasPrecision(18,3);
            this.Property(o => o.Comment).IsUnicode();
            this.Property(o => o.Comment).HasMaxLength(50);
            this.Property(o => o.Shipper).IsUnicode();
            this.Property(o => o.Shipper).HasMaxLength(50);
            this.Property(o => o.Shipper_Telephone).IsUnicode();
            this.Property(o => o.Shipper_Telephone).HasMaxLength(50);
            this.Property(o => o.Carrier).IsUnicode();
            this.Property(o => o.Carrier).HasMaxLength(50);
            this.Property(o => o.Carrier_Telephone).IsUnicode();
            this.Property(o => o.Carrier_Telephone).HasMaxLength(50);
            this.Property(o => o.Status).IsRequired();
        }
    }
}
