if not exists (select * from aspnet_SchemaVersions where Feature='common' and CompatibleSchemaVersion='1')
insert into aspnet_SchemaVersions(Feature,CompatibleSchemaVersion,IsCurrentVersion) values('common','1',1)
if not exists (select * from aspnet_SchemaVersions where Feature='health monitoring' and CompatibleSchemaVersion='1')
insert into aspnet_SchemaVersions(Feature,CompatibleSchemaVersion,IsCurrentVersion) values('health monitoring','1',1)
if not exists (select * from aspnet_SchemaVersions where Feature='membership' and CompatibleSchemaVersion='1')
insert into aspnet_SchemaVersions(Feature,CompatibleSchemaVersion,IsCurrentVersion) values('membership','1',1)
if not exists (select * from aspnet_SchemaVersions where Feature='personalization' and CompatibleSchemaVersion='1')
insert into aspnet_SchemaVersions(Feature,CompatibleSchemaVersion,IsCurrentVersion) values('personalization','1',1)
if not exists (select * from aspnet_SchemaVersions where Feature='profile' and CompatibleSchemaVersion='1')
insert into aspnet_SchemaVersions(Feature,CompatibleSchemaVersion,IsCurrentVersion) values('profile','1',1)
if not exists (select * from aspnet_SchemaVersions where Feature='role manager' and CompatibleSchemaVersion='1')
insert into aspnet_SchemaVersions(Feature,CompatibleSchemaVersion,IsCurrentVersion) values('role manager','1',1)
