if not exists (select * from NameCode where Type='BillType' and Code='CardConsumeWindow')
insert into NameCode(Type,Code,Name) values('BillType','CardConsumeWindow','会员卡消费')
if not exists (select * from NameCode where Type='BillType' and Code='CardConsume3Window')
insert into NameCode(Type,Code,Name) values('BillType','CardConsume3Window','打折卡消费')
if not exists (select * from NameCode where Type='BillType' and Code='CardInMoneyWindow')
insert into NameCode(Type,Code,Name) values('BillType','CardInMoneyWindow','会员卡充值')
if not exists (select * from NameCode where Type='BillType' and Code='NoMemberConsumeWindow')
insert into NameCode(Type,Code,Name) values('BillType','NoMemberConsumeWindow','非会员消费')
if not exists (select * from NameCode where Type='BillType' and Code='PointsExchangeWindow')
insert into NameCode(Type,Code,Name) values('BillType','PointsExchangeWindow','会员积分兑换')
if not exists (select * from NameCode where Type='BillType' and Code='WRCardConsumeWindow')
insert into NameCode(Type,Code,Name) values('BillType','WRCardConsumeWindow','西餐厅会员卡消费')
if not exists (select * from NameCode where Type='BillType' and Code='WRNoMemberConsumeWindow')
insert into NameCode(Type,Code,Name) values('BillType','WRNoMemberConsumeWindow','西餐厅非会员消费')
if not exists (select * from NameCode where Type='BillType' and Code='WRCardConsume3Window')
insert into NameCode(Type,Code,Name) values('BillType','WRCardConsume3Window','西餐厅打折卡消费')
if not exists (select * from NameCode where Type='BillType' and Code='Sticker')
insert into NameCode(Type,Code,Name) values('BillType','Sticker','不干胶')

if not exists (select * from NameCode where Type='CardStatus' and Code='0')
insert into NameCode(Type,Code,Name) values('CardStatus','0','正常在用')
if not exists (select * from NameCode where Type='CardStatus' and Code='1')
insert into NameCode(Type,Code,Name) values('CardStatus','1','已挂失')
if not exists (select * from NameCode where Type='CardStatus' and Code='2')
insert into NameCode(Type,Code,Name) values('CardStatus','2','已补卡')

if not exists (select * from NameCode where Type='OrderBookStatus' and Code='0')
insert into NameCode(Type,Code,Name) values('OrderBookStatus','0','已预定')
if not exists (select * from NameCode where Type='OrderBookStatus' and Code='1')
insert into NameCode(Type,Code,Name) values('OrderBookStatus','1','已取消预订')
if not exists (select * from NameCode where Type='OrderBookStatus' and Code='2')
insert into NameCode(Type,Code,Name) values('OrderBookStatus','2','已开台')

if not exists (select * from NameCode where Type='OrderBookDeskStatus' and Code='0')
insert into NameCode(Type,Code,Name) values('OrderBookDeskStatus','0','已预定')
if not exists (select * from NameCode where Type='OrderBookDeskStatus' and Code='0')
insert into NameCode(Type,Code,Name) values('OrderBookDeskStatus','1','已撤销')

if not exists (select * from NameCode where Type='CupType' and Code='-1')
insert into NameCode(Type,Code,Name) values('CupType','-1','标准杯')
if not exists (select * from NameCode where Type='CupType' and Code='0')
insert into NameCode(Type,Code,Name) values('CupType','0','大杯')

if not exists (select * from NameCode where Type='OrderDishStatus' and Code='0')
insert into NameCode(Type,Code,Name) values('OrderDishStatus','0','已开台')
if not exists (select * from NameCode where Type='OrderDishStatus' and Code='1')
insert into NameCode(Type,Code,Name) values('OrderDishStatus','1','已结账')
if not exists (select * from NameCode where Type='OrderDishStatus' and Code='2')
insert into NameCode(Type,Code,Name) values('OrderDishStatus','2','已撤销')
if not exists (select * from NameCode where Type='OrderDishStatus' and Code='3')
insert into NameCode(Type,Code,Name) values('OrderDishStatus','3','已下单')

if not exists (select * from NameCode where Type='OrderMenuStatus' and Code='0')
insert into NameCode(Type,Code,Name) values('OrderMenuStatus','0','正常')
if not exists (select * from NameCode where Type='OrderMenuStatus' and Code='1')
insert into NameCode(Type,Code,Name) values('OrderMenuStatus','1','退菜')
if not exists (select * from NameCode where Type='OrderMenuStatus' and Code='2')
insert into NameCode(Type,Code,Name) values('OrderMenuStatus','2','下单')
if not exists (select * from NameCode where Type='OrderMenuStatus' and Code='3')
insert into NameCode(Type,Code,Name) values('OrderMenuStatus','3','缺菜')
if not exists (select * from NameCode where Type='OrderMenuStatus' and Code='4')
insert into NameCode(Type,Code,Name) values('OrderMenuStatus','4','催菜')
if not exists (select * from NameCode where Type='OrderMenuStatus' and Code='5')
insert into NameCode(Type,Code,Name) values('OrderMenuStatus','5','制作')
if not exists (select * from NameCode where Type='OrderMenuStatus' and Code='6')
insert into NameCode(Type,Code,Name) values('OrderMenuStatus','6','出菜')
if not exists (select * from NameCode where Type='OrderMenuStatus' and Code='7')
insert into NameCode(Type,Code,Name) values('OrderMenuStatus','7','出菜后退菜')
if not exists (select * from NameCode where Type='OrderMenuStatus' and Code='8')
insert into NameCode(Type,Code,Name) values('OrderMenuStatus','8','结账')

if not exists (select * from NameCode where Type='ConsumeType' and Code='0')
insert into NameCode(Type,Code,Name) values('ConsumeType','0','会员卡消费')
if not exists (select * from NameCode where Type='ConsumeType' and Code='1')
insert into NameCode(Type,Code,Name) values('ConsumeType','1','非会员消费')
if not exists (select * from NameCode where Type='ConsumeType' and Code='2')
insert into NameCode(Type,Code,Name) values('ConsumeType','2','会员积分兑换')
if not exists (select * from NameCode where Type='ConsumeType' and Code='3')
insert into NameCode(Type,Code,Name) values('ConsumeType','3','打折卡消费')

if not exists (select * from NameCode where Type='RechargeType' and Code='0')
insert into NameCode(Type,Code,Name) values('RechargeType','0','普通充值')
if not exists (select * from NameCode where Type='RechargeType' and Code='1')
insert into NameCode(Type,Code,Name) values('RechargeType','1','补卡充值')
if not exists (select * from NameCode where Type='RechargeType' and Code='2')
insert into NameCode(Type,Code,Name) values('RechargeType','2','发卡充值')
if not exists (select * from NameCode where Type='RechargeType' and Code='3')
insert into NameCode(Type,Code,Name) values('RechargeType','3','补卡费')

if not exists (select * from NameCode where Type='SectionType' and Code='0')
insert into NameCode(Type,Code,Name) values('SectionType','0','后厨')
if not exists (select * from NameCode where Type='SectionType' and Code='1')
insert into NameCode(Type,Code,Name) values('SectionType','1','吧台')
if not exists (select * from NameCode where Type='SectionType' and Code='2')
insert into NameCode(Type,Code,Name) values('SectionType','2','前厅')

delete namecode where Type = 'Dept_DeptType'
if not exists (select * from NameCode where Type='DeptType' and Code='0')
insert into NameCode(Type,Code,Name) values('DeptType','0','零售型')
if not exists (select * from NameCode where Type='DeptType' and Code='1')
insert into NameCode(Type,Code,Name) values('DeptType','1','坐店服务型')


if not exists (select * from NameCode where Type='ReceiptStatus' and Code='0')
insert into NameCode(Type,Code,Name) values('ReceiptStatus','0','正常')
if not exists (select * from NameCode where Type='ReceiptStatus' and Code='1')
insert into NameCode(Type,Code,Name) values('ReceiptStatus','1','完成')

if not exists (select * from NameCode where Type='PayType' and Code='0')
insert into NameCode(Type,Code,Name) values('PayType','0','现金')
if not exists (select * from NameCode where Type='PayType' and Code='1')
insert into NameCode(Type,Code,Name) values('PayType','1','银行卡')
if not exists (select * from NameCode where Type='PayType' and Code='2')
insert into NameCode(Type,Code,Name) values('PayType','2','代金券')
if not exists (select * from NameCode where Type='PayType' and Code='99')
insert into NameCode(Type,Code,Name) values('PayType','99','其它')



if not exists (select * from NameCode where Type='RoomStatus' and Code='0')
insert into NameCode(Type,Code,Name) values('RoomStatus','0','不用')
if not exists (select * from NameCode where Type='RoomStatus' and Code='1')
insert into NameCode(Type,Code,Name) values('RoomStatus','1','在用')

if not exists (select * from NameCode where Type='DeskStatus' and Code='0')
insert into NameCode(Type,Code,Name) values('DeskStatus','0','不用')
if not exists (select * from NameCode where Type='DeskStatus' and Code='1')
insert into NameCode(Type,Code,Name) values('DeskStatus','1','在用')

if not exists (select * from NameCode where Type='IPadStatus' and Code='0')
insert into NameCode(Type,Code,Name) values('IPadStatus','0','不用')
if not exists (select * from NameCode where Type='IPadStatus' and Code='1')
insert into NameCode(Type,Code,Name) values('IPadStatus','1','在用')


if not exists (select * from NameCode where Type='AuthorityType' and Code='0')
insert into NameCode(Type,Code,Name) values('AuthorityType','0','所有')
if not exists (select * from NameCode where Type='AuthorityType' and Code='1')
insert into NameCode(Type,Code,Name) values('AuthorityType','1','部门')
if not exists (select * from NameCode where Type='AuthorityType' and Code='2')
insert into NameCode(Type,Code,Name) values('AuthorityType','2','门店')
if not exists (select * from NameCode where Type='AuthorityType' and Code='3')
insert into NameCode(Type,Code,Name) values('AuthorityType','3','本人')